/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChiffreAffaires service. Represents a row in the &quot;chiffre_affaires&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.ChiffreAffairesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.ChiffreAffairesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChiffreAffaires
 * @generated
 */
@ProviderType
public interface ChiffreAffairesModel extends BaseModel<ChiffreAffaires> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chiffre affaires model instance should use the {@link ChiffreAffaires} interface instead.
	 */

	/**
	 * Returns the primary key of this chiffre affaires.
	 *
	 * @return the primary key of this chiffre affaires
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chiffre affaires.
	 *
	 * @param primaryKey the primary key of this chiffre affaires
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chiffre affaires.
	 *
	 * @return the ID of this chiffre affaires
	 */
	public long getId();

	/**
	 * Sets the ID of this chiffre affaires.
	 *
	 * @param id the ID of this chiffre affaires
	 */
	public void setId(long id);

	/**
	 * Returns the terminal ID of this chiffre affaires.
	 *
	 * @return the terminal ID of this chiffre affaires
	 */
	public long getTerminalId();

	/**
	 * Sets the terminal ID of this chiffre affaires.
	 *
	 * @param terminalId the terminal ID of this chiffre affaires
	 */
	public void setTerminalId(long terminalId);

	/**
	 * Returns the brut of this chiffre affaires.
	 *
	 * @return the brut of this chiffre affaires
	 */
	public long getBrut();

	/**
	 * Sets the brut of this chiffre affaires.
	 *
	 * @param brut the brut of this chiffre affaires
	 */
	public void setBrut(long brut);

	/**
	 * Returns the paiement of this chiffre affaires.
	 *
	 * @return the paiement of this chiffre affaires
	 */
	public long getPaiement();

	/**
	 * Sets the paiement of this chiffre affaires.
	 *
	 * @param paiement the paiement of this chiffre affaires
	 */
	public void setPaiement(long paiement);

	/**
	 * Returns the annulation of this chiffre affaires.
	 *
	 * @return the annulation of this chiffre affaires
	 */
	public long getAnnulation();

	/**
	 * Sets the annulation of this chiffre affaires.
	 *
	 * @param annulation the annulation of this chiffre affaires
	 */
	public void setAnnulation(long annulation);

	/**
	 * Returns the remboursement of this chiffre affaires.
	 *
	 * @return the remboursement of this chiffre affaires
	 */
	public long getRemboursement();

	/**
	 * Sets the remboursement of this chiffre affaires.
	 *
	 * @param remboursement the remboursement of this chiffre affaires
	 */
	public void setRemboursement(long remboursement);

	/**
	 * Returns the ventes of this chiffre affaires.
	 *
	 * @return the ventes of this chiffre affaires
	 */
	public long getVentes();

	/**
	 * Sets the ventes of this chiffre affaires.
	 *
	 * @param ventes the ventes of this chiffre affaires
	 */
	public void setVentes(long ventes);

	/**
	 * Returns the balance of this chiffre affaires.
	 *
	 * @return the balance of this chiffre affaires
	 */
	public long getBalance();

	/**
	 * Sets the balance of this chiffre affaires.
	 *
	 * @param balance the balance of this chiffre affaires
	 */
	public void setBalance(long balance);

	/**
	 * Returns the deposit of this chiffre affaires.
	 *
	 * @return the deposit of this chiffre affaires
	 */
	public long getDeposit();

	/**
	 * Sets the deposit of this chiffre affaires.
	 *
	 * @param deposit the deposit of this chiffre affaires
	 */
	public void setDeposit(long deposit);

	/**
	 * Returns the date of this chiffre affaires.
	 *
	 * @return the date of this chiffre affaires
	 */
	public Date getDate();

	/**
	 * Sets the date of this chiffre affaires.
	 *
	 * @param date the date of this chiffre affaires
	 */
	public void setDate(Date date);

	/**
	 * Returns the created at of this chiffre affaires.
	 *
	 * @return the created at of this chiffre affaires
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this chiffre affaires.
	 *
	 * @param createdAt the created at of this chiffre affaires
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this chiffre affaires.
	 *
	 * @return the updated at of this chiffre affaires
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this chiffre affaires.
	 *
	 * @param updatedAt the updated at of this chiffre affaires
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public ChiffreAffaires cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}