/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Commission service. Represents a row in the &quot;commissions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.CommissionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.CommissionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Commission
 * @generated
 */
@ProviderType
public interface CommissionModel extends BaseModel<Commission> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commission model instance should use the {@link Commission} interface instead.
	 */

	/**
	 * Returns the primary key of this commission.
	 *
	 * @return the primary key of this commission
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commission.
	 *
	 * @param primaryKey the primary key of this commission
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this commission.
	 *
	 * @return the ID of this commission
	 */
	public long getId();

	/**
	 * Sets the ID of this commission.
	 *
	 * @param id the ID of this commission
	 */
	public void setId(long id);

	/**
	 * Returns the code of this commission.
	 *
	 * @return the code of this commission
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this commission.
	 *
	 * @param code the code of this commission
	 */
	public void setCode(String code);

	/**
	 * Returns the terminal ID of this commission.
	 *
	 * @return the terminal ID of this commission
	 */
	public long getTerminalId();

	/**
	 * Sets the terminal ID of this commission.
	 *
	 * @param terminalId the terminal ID of this commission
	 */
	public void setTerminalId(long terminalId);

	/**
	 * Returns the nombre terminal of this commission.
	 *
	 * @return the nombre terminal of this commission
	 */
	public int getNombreTerminal();

	/**
	 * Sets the nombre terminal of this commission.
	 *
	 * @param nombreTerminal the nombre terminal of this commission
	 */
	public void setNombreTerminal(int nombreTerminal);

	/**
	 * Returns the paye of this commission.
	 *
	 * @return the paye of this commission
	 */
	public boolean getPaye();

	/**
	 * Returns <code>true</code> if this commission is paye.
	 *
	 * @return <code>true</code> if this commission is paye; <code>false</code> otherwise
	 */
	public boolean isPaye();

	/**
	 * Sets whether this commission is paye.
	 *
	 * @param paye the paye of this commission
	 */
	public void setPaye(boolean paye);

	/**
	 * Returns the libelle of this commission.
	 *
	 * @return the libelle of this commission
	 */
	@AutoEscape
	public String getLibelle();

	/**
	 * Sets the libelle of this commission.
	 *
	 * @param libelle the libelle of this commission
	 */
	public void setLibelle(String libelle);

	/**
	 * Returns the status of this commission.
	 *
	 * @return the status of this commission
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this commission.
	 *
	 * @param status the status of this commission
	 */
	public void setStatus(String status);

	/**
	 * Returns the created at of this commission.
	 *
	 * @return the created at of this commission
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this commission.
	 *
	 * @param createdAt the created at of this commission
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this commission.
	 *
	 * @return the updated at of this commission
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this commission.
	 *
	 * @param updatedAt the updated at of this commission
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Commission cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}