/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Commercial service. Represents a row in the &quot;commerciaux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.CommercialModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.CommercialImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Commercial
 * @generated
 */
@ProviderType
public interface CommercialModel extends BaseModel<Commercial> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commercial model instance should use the {@link Commercial} interface instead.
	 */

	/**
	 * Returns the primary key of this commercial.
	 *
	 * @return the primary key of this commercial
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commercial.
	 *
	 * @param primaryKey the primary key of this commercial
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this commercial.
	 *
	 * @return the ID of this commercial
	 */
	public long getId();

	/**
	 * Sets the ID of this commercial.
	 *
	 * @param id the ID of this commercial
	 */
	public void setId(long id);

	/**
	 * Returns the nom of this commercial.
	 *
	 * @return the nom of this commercial
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this commercial.
	 *
	 * @param nom the nom of this commercial
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenoms of this commercial.
	 *
	 * @return the prenoms of this commercial
	 */
	@AutoEscape
	public String getPrenoms();

	/**
	 * Sets the prenoms of this commercial.
	 *
	 * @param prenoms the prenoms of this commercial
	 */
	public void setPrenoms(String prenoms);

	/**
	 * Returns the telephone of this commercial.
	 *
	 * @return the telephone of this commercial
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this commercial.
	 *
	 * @param telephone the telephone of this commercial
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the email of this commercial.
	 *
	 * @return the email of this commercial
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this commercial.
	 *
	 * @param email the email of this commercial
	 */
	public void setEmail(String email);

	/**
	 * Returns the matricule of this commercial.
	 *
	 * @return the matricule of this commercial
	 */
	@AutoEscape
	public String getMatricule();

	/**
	 * Sets the matricule of this commercial.
	 *
	 * @param matricule the matricule of this commercial
	 */
	public void setMatricule(String matricule);

	/**
	 * Returns the statut of this commercial.
	 *
	 * @return the statut of this commercial
	 */
	@AutoEscape
	public String getStatut();

	/**
	 * Sets the statut of this commercial.
	 *
	 * @param statut the statut of this commercial
	 */
	public void setStatut(String statut);

	/**
	 * Returns the superviseur ID of this commercial.
	 *
	 * @return the superviseur ID of this commercial
	 */
	public long getSuperviseurId();

	/**
	 * Sets the superviseur ID of this commercial.
	 *
	 * @param superviseurId the superviseur ID of this commercial
	 */
	public void setSuperviseurId(long superviseurId);

	/**
	 * Returns the created at of this commercial.
	 *
	 * @return the created at of this commercial
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this commercial.
	 *
	 * @param createdAt the created at of this commercial
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this commercial.
	 *
	 * @return the updated at of this commercial
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this commercial.
	 *
	 * @param updatedAt the updated at of this commercial
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Commercial cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}