/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ConcessionnaireProduit service. Represents a row in the &quot;concessionnaire_produit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.ConcessionnaireProduitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.ConcessionnaireProduitImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcessionnaireProduit
 * @generated
 */
@ProviderType
public interface ConcessionnaireProduitModel
	extends BaseModel<ConcessionnaireProduit> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a concessionnaire produit model instance should use the {@link ConcessionnaireProduit} interface instead.
	 */

	/**
	 * Returns the primary key of this concessionnaire produit.
	 *
	 * @return the primary key of this concessionnaire produit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this concessionnaire produit.
	 *
	 * @param primaryKey the primary key of this concessionnaire produit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this concessionnaire produit.
	 *
	 * @return the ID of this concessionnaire produit
	 */
	public long getId();

	/**
	 * Sets the ID of this concessionnaire produit.
	 *
	 * @param id the ID of this concessionnaire produit
	 */
	public void setId(long id);

	/**
	 * Returns the concessionnaire ID of this concessionnaire produit.
	 *
	 * @return the concessionnaire ID of this concessionnaire produit
	 */
	public long getConcessionnaireId();

	/**
	 * Sets the concessionnaire ID of this concessionnaire produit.
	 *
	 * @param concessionnaireId the concessionnaire ID of this concessionnaire produit
	 */
	public void setConcessionnaireId(long concessionnaireId);

	/**
	 * Returns the produit ID of this concessionnaire produit.
	 *
	 * @return the produit ID of this concessionnaire produit
	 */
	public long getProduitId();

	/**
	 * Sets the produit ID of this concessionnaire produit.
	 *
	 * @param produitId the produit ID of this concessionnaire produit
	 */
	public void setProduitId(long produitId);

	/**
	 * Returns the site ID of this concessionnaire produit.
	 *
	 * @return the site ID of this concessionnaire produit
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this concessionnaire produit.
	 *
	 * @param siteId the site ID of this concessionnaire produit
	 */
	public void setSiteId(long siteId);

	/**
	 * Returns the code of this concessionnaire produit.
	 *
	 * @return the code of this concessionnaire produit
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this concessionnaire produit.
	 *
	 * @param code the code of this concessionnaire produit
	 */
	public void setCode(String code);

	/**
	 * Returns the concessionnaire code of this concessionnaire produit.
	 *
	 * @return the concessionnaire code of this concessionnaire produit
	 */
	@AutoEscape
	public String getConcessionnaireCode();

	/**
	 * Sets the concessionnaire code of this concessionnaire produit.
	 *
	 * @param concessionnaireCode the concessionnaire code of this concessionnaire produit
	 */
	public void setConcessionnaireCode(String concessionnaireCode);

	/**
	 * Returns the active of this concessionnaire produit.
	 *
	 * @return the active of this concessionnaire produit
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this concessionnaire produit is active.
	 *
	 * @return <code>true</code> if this concessionnaire produit is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this concessionnaire produit is active.
	 *
	 * @param active the active of this concessionnaire produit
	 */
	public void setActive(boolean active);

	/**
	 * Returns the created at of this concessionnaire produit.
	 *
	 * @return the created at of this concessionnaire produit
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this concessionnaire produit.
	 *
	 * @param createdAt the created at of this concessionnaire produit
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this concessionnaire produit.
	 *
	 * @return the updated at of this concessionnaire produit
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this concessionnaire produit.
	 *
	 * @param updatedAt the updated at of this concessionnaire produit
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public ConcessionnaireProduit cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}