/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Concessionnaire service. Represents a row in the &quot;concessionnaires&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.ConcessionnaireModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.ConcessionnaireImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Concessionnaire
 * @generated
 */
@ProviderType
public interface ConcessionnaireModel extends BaseModel<Concessionnaire> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a concessionnaire model instance should use the {@link Concessionnaire} interface instead.
	 */

	/**
	 * Returns the primary key of this concessionnaire.
	 *
	 * @return the primary key of this concessionnaire
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this concessionnaire.
	 *
	 * @param primaryKey the primary key of this concessionnaire
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this concessionnaire.
	 *
	 * @return the ID of this concessionnaire
	 */
	public long getId();

	/**
	 * Sets the ID of this concessionnaire.
	 *
	 * @param id the ID of this concessionnaire
	 */
	public void setId(long id);

	/**
	 * Returns the uid of this concessionnaire.
	 *
	 * @return the uid of this concessionnaire
	 */
	@AutoEscape
	public String getUid();

	/**
	 * Sets the uid of this concessionnaire.
	 *
	 * @param uid the uid of this concessionnaire
	 */
	public void setUid(String uid);

	/**
	 * Returns the nom of this concessionnaire.
	 *
	 * @return the nom of this concessionnaire
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this concessionnaire.
	 *
	 * @param nom the nom of this concessionnaire
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenoms of this concessionnaire.
	 *
	 * @return the prenoms of this concessionnaire
	 */
	@AutoEscape
	public String getPrenoms();

	/**
	 * Sets the prenoms of this concessionnaire.
	 *
	 * @param prenoms the prenoms of this concessionnaire
	 */
	public void setPrenoms(String prenoms);

	/**
	 * Returns the telephone of this concessionnaire.
	 *
	 * @return the telephone of this concessionnaire
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this concessionnaire.
	 *
	 * @param telephone the telephone of this concessionnaire
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the email of this concessionnaire.
	 *
	 * @return the email of this concessionnaire
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this concessionnaire.
	 *
	 * @param email the email of this concessionnaire
	 */
	public void setEmail(String email);

	@Override
	public Concessionnaire cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}