/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Objectif service. Represents a row in the &quot;objectifs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.ObjectifModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.ObjectifImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Objectif
 * @generated
 */
@ProviderType
public interface ObjectifModel extends BaseModel<Objectif> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a objectif model instance should use the {@link Objectif} interface instead.
	 */

	/**
	 * Returns the primary key of this objectif.
	 *
	 * @return the primary key of this objectif
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this objectif.
	 *
	 * @param primaryKey the primary key of this objectif
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this objectif.
	 *
	 * @return the ID of this objectif
	 */
	public long getId();

	/**
	 * Sets the ID of this objectif.
	 *
	 * @param id the ID of this objectif
	 */
	public void setId(long id);

	/**
	 * Returns the commercial ID of this objectif.
	 *
	 * @return the commercial ID of this objectif
	 */
	public long getCommercialId();

	/**
	 * Sets the commercial ID of this objectif.
	 *
	 * @param commercialId the commercial ID of this objectif
	 */
	public void setCommercialId(long commercialId);

	/**
	 * Returns the type of this objectif.
	 *
	 * @return the type of this objectif
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this objectif.
	 *
	 * @param type the type of this objectif
	 */
	public void setType(String type);

	/**
	 * Returns the periode of this objectif.
	 *
	 * @return the periode of this objectif
	 */
	@AutoEscape
	public String getPeriode();

	/**
	 * Sets the periode of this objectif.
	 *
	 * @param periode the periode of this objectif
	 */
	public void setPeriode(String periode);

	/**
	 * Returns the valeur cible of this objectif.
	 *
	 * @return the valeur cible of this objectif
	 */
	public int getValeurCible();

	/**
	 * Sets the valeur cible of this objectif.
	 *
	 * @param valeurCible the valeur cible of this objectif
	 */
	public void setValeurCible(int valeurCible);

	/**
	 * Returns the valeur reelle of this objectif.
	 *
	 * @return the valeur reelle of this objectif
	 */
	public int getValeurReelle();

	/**
	 * Sets the valeur reelle of this objectif.
	 *
	 * @param valeurReelle the valeur reelle of this objectif
	 */
	public void setValeurReelle(int valeurReelle);

	/**
	 * Returns the mois of this objectif.
	 *
	 * @return the mois of this objectif
	 */
	public int getMois();

	/**
	 * Sets the mois of this objectif.
	 *
	 * @param mois the mois of this objectif
	 */
	public void setMois(int mois);

	/**
	 * Returns the trimestre of this objectif.
	 *
	 * @return the trimestre of this objectif
	 */
	public int getTrimestre();

	/**
	 * Sets the trimestre of this objectif.
	 *
	 * @param trimestre the trimestre of this objectif
	 */
	public void setTrimestre(int trimestre);

	/**
	 * Returns the annee of this objectif.
	 *
	 * @return the annee of this objectif
	 */
	public int getAnnee();

	/**
	 * Sets the annee of this objectif.
	 *
	 * @param annee the annee of this objectif
	 */
	public void setAnnee(int annee);

	/**
	 * Returns the created at of this objectif.
	 *
	 * @return the created at of this objectif
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this objectif.
	 *
	 * @param createdAt the created at of this objectif
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this objectif.
	 *
	 * @return the updated at of this objectif
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this objectif.
	 *
	 * @param updatedAt the updated at of this objectif
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Objectif cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}