/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Operation service. Represents a row in the &quot;operations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.OperationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.OperationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Operation
 * @generated
 */
@ProviderType
public interface OperationModel extends BaseModel<Operation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a operation model instance should use the {@link Operation} interface instead.
	 */

	/**
	 * Returns the primary key of this operation.
	 *
	 * @return the primary key of this operation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this operation.
	 *
	 * @param primaryKey the primary key of this operation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this operation.
	 *
	 * @return the ID of this operation
	 */
	public long getId();

	/**
	 * Sets the ID of this operation.
	 *
	 * @param id the ID of this operation
	 */
	public void setId(long id);

	/**
	 * Returns the code of this operation.
	 *
	 * @return the code of this operation
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this operation.
	 *
	 * @param code the code of this operation
	 */
	public void setCode(String code);

	/**
	 * Returns the libelle of this operation.
	 *
	 * @return the libelle of this operation
	 */
	@AutoEscape
	public String getLibelle();

	/**
	 * Sets the libelle of this operation.
	 *
	 * @param libelle the libelle of this operation
	 */
	public void setLibelle(String libelle);

	/**
	 * Returns the reference of this operation.
	 *
	 * @return the reference of this operation
	 */
	@AutoEscape
	public String getReference();

	/**
	 * Sets the reference of this operation.
	 *
	 * @param reference the reference of this operation
	 */
	public void setReference(String reference);

	/**
	 * Returns the montant of this operation.
	 *
	 * @return the montant of this operation
	 */
	public long getMontant();

	/**
	 * Sets the montant of this operation.
	 *
	 * @param montant the montant of this operation
	 */
	public void setMontant(long montant);

	/**
	 * Returns the montant reel of this operation.
	 *
	 * @return the montant reel of this operation
	 */
	public long getMontantReel();

	/**
	 * Sets the montant reel of this operation.
	 *
	 * @param montantReel the montant reel of this operation
	 */
	public void setMontantReel(long montantReel);

	/**
	 * Returns the statut of this operation.
	 *
	 * @return the statut of this operation
	 */
	@AutoEscape
	public String getStatut();

	/**
	 * Sets the statut of this operation.
	 *
	 * @param statut the statut of this operation
	 */
	public void setStatut(String statut);

	/**
	 * Returns the terminal ID of this operation.
	 *
	 * @return the terminal ID of this operation
	 */
	public long getTerminalId();

	/**
	 * Sets the terminal ID of this operation.
	 *
	 * @param terminalId the terminal ID of this operation
	 */
	public void setTerminalId(long terminalId);

	/**
	 * Returns the guichet of this operation.
	 *
	 * @return the guichet of this operation
	 */
	@AutoEscape
	public String getGuichet();

	/**
	 * Sets the guichet of this operation.
	 *
	 * @param guichet the guichet of this operation
	 */
	public void setGuichet(String guichet);

	/**
	 * Returns the date operation of this operation.
	 *
	 * @return the date operation of this operation
	 */
	public Date getDateOperation();

	/**
	 * Sets the date operation of this operation.
	 *
	 * @param dateOperation the date operation of this operation
	 */
	public void setDateOperation(Date dateOperation);

	/**
	 * Returns the created at of this operation.
	 *
	 * @return the created at of this operation
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this operation.
	 *
	 * @param createdAt the created at of this operation
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this operation.
	 *
	 * @return the updated at of this operation
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this operation.
	 *
	 * @param updatedAt the updated at of this operation
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Operation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}