/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Produit service. Represents a row in the &quot;produits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.ProduitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.ProduitImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Produit
 * @generated
 */
@ProviderType
public interface ProduitModel extends BaseModel<Produit> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a produit model instance should use the {@link Produit} interface instead.
	 */

	/**
	 * Returns the primary key of this produit.
	 *
	 * @return the primary key of this produit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this produit.
	 *
	 * @param primaryKey the primary key of this produit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this produit.
	 *
	 * @return the ID of this produit
	 */
	public long getId();

	/**
	 * Sets the ID of this produit.
	 *
	 * @param id the ID of this produit
	 */
	public void setId(long id);

	/**
	 * Returns the code of this produit.
	 *
	 * @return the code of this produit
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this produit.
	 *
	 * @param code the code of this produit
	 */
	public void setCode(String code);

	/**
	 * Returns the libelle of this produit.
	 *
	 * @return the libelle of this produit
	 */
	@AutoEscape
	public String getLibelle();

	/**
	 * Sets the libelle of this produit.
	 *
	 * @param libelle the libelle of this produit
	 */
	public void setLibelle(String libelle);

	/**
	 * Returns the abreviation of this produit.
	 *
	 * @return the abreviation of this produit
	 */
	@AutoEscape
	public String getAbreviation();

	/**
	 * Sets the abreviation of this produit.
	 *
	 * @param abreviation the abreviation of this produit
	 */
	public void setAbreviation(String abreviation);

	/**
	 * Returns the active of this produit.
	 *
	 * @return the active of this produit
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this produit is active.
	 *
	 * @return <code>true</code> if this produit is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this produit is active.
	 *
	 * @param active the active of this produit
	 */
	public void setActive(boolean active);

	/**
	 * Returns the created at of this produit.
	 *
	 * @return the created at of this produit
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this produit.
	 *
	 * @param createdAt the created at of this produit
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this produit.
	 *
	 * @return the updated at of this produit
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this produit.
	 *
	 * @param updatedAt the updated at of this produit
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Produit cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}