/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SiteCommercial service. Represents a row in the &quot;site_commerciaux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.SiteCommercialModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.SiteCommercialImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteCommercial
 * @generated
 */
@ProviderType
public interface SiteCommercialModel extends BaseModel<SiteCommercial> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site commercial model instance should use the {@link SiteCommercial} interface instead.
	 */

	/**
	 * Returns the primary key of this site commercial.
	 *
	 * @return the primary key of this site commercial
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site commercial.
	 *
	 * @param primaryKey the primary key of this site commercial
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this site commercial.
	 *
	 * @return the ID of this site commercial
	 */
	public long getId();

	/**
	 * Sets the ID of this site commercial.
	 *
	 * @param id the ID of this site commercial
	 */
	public void setId(long id);

	/**
	 * Returns the site ID of this site commercial.
	 *
	 * @return the site ID of this site commercial
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this site commercial.
	 *
	 * @param siteId the site ID of this site commercial
	 */
	public void setSiteId(long siteId);

	/**
	 * Returns the commercial ID of this site commercial.
	 *
	 * @return the commercial ID of this site commercial
	 */
	public long getCommercialId();

	/**
	 * Sets the commercial ID of this site commercial.
	 *
	 * @param commercialId the commercial ID of this site commercial
	 */
	public void setCommercialId(long commercialId);

	/**
	 * Returns the date debut of this site commercial.
	 *
	 * @return the date debut of this site commercial
	 */
	public Date getDateDebut();

	/**
	 * Sets the date debut of this site commercial.
	 *
	 * @param dateDebut the date debut of this site commercial
	 */
	public void setDateDebut(Date dateDebut);

	/**
	 * Returns the date fin of this site commercial.
	 *
	 * @return the date fin of this site commercial
	 */
	public Date getDateFin();

	/**
	 * Sets the date fin of this site commercial.
	 *
	 * @param dateFin the date fin of this site commercial
	 */
	public void setDateFin(Date dateFin);

	/**
	 * Returns the is principal of this site commercial.
	 *
	 * @return the is principal of this site commercial
	 */
	public boolean getIsPrincipal();

	/**
	 * Returns <code>true</code> if this site commercial is is principal.
	 *
	 * @return <code>true</code> if this site commercial is is principal; <code>false</code> otherwise
	 */
	public boolean isIsPrincipal();

	/**
	 * Sets whether this site commercial is is principal.
	 *
	 * @param isPrincipal the is principal of this site commercial
	 */
	public void setIsPrincipal(boolean isPrincipal);

	/**
	 * Returns the created at of this site commercial.
	 *
	 * @return the created at of this site commercial
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this site commercial.
	 *
	 * @param createdAt the created at of this site commercial
	 */
	public void setCreatedAt(Date createdAt);

	@Override
	public SiteCommercial cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}