/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Site service. Represents a row in the &quot;sites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.SiteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.SiteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Site
 * @generated
 */
@ProviderType
public interface SiteModel extends BaseModel<Site> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site model instance should use the {@link Site} interface instead.
	 */

	/**
	 * Returns the primary key of this site.
	 *
	 * @return the primary key of this site
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site.
	 *
	 * @param primaryKey the primary key of this site
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this site.
	 *
	 * @return the ID of this site
	 */
	public long getId();

	/**
	 * Sets the ID of this site.
	 *
	 * @param id the ID of this site
	 */
	public void setId(long id);

	/**
	 * Returns the libelle of this site.
	 *
	 * @return the libelle of this site
	 */
	@AutoEscape
	public String getLibelle();

	/**
	 * Sets the libelle of this site.
	 *
	 * @param libelle the libelle of this site
	 */
	public void setLibelle(String libelle);

	/**
	 * Returns the type of this site.
	 *
	 * @return the type of this site
	 */
	public int getType();

	/**
	 * Sets the type of this site.
	 *
	 * @param type the type of this site
	 */
	public void setType(int type);

	/**
	 * Returns the parent ID of this site.
	 *
	 * @return the parent ID of this site
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this site.
	 *
	 * @param parentId the parent ID of this site
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the code of this site.
	 *
	 * @return the code of this site
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this site.
	 *
	 * @param code the code of this site
	 */
	public void setCode(String code);

	/**
	 * Returns the code provinov of this site.
	 *
	 * @return the code provinov of this site
	 */
	@AutoEscape
	public String getCodeProvinov();

	/**
	 * Sets the code provinov of this site.
	 *
	 * @param codeProvinov the code provinov of this site
	 */
	public void setCodeProvinov(String codeProvinov);

	/**
	 * Returns the status of this site.
	 *
	 * @return the status of this site
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this site is status.
	 *
	 * @return <code>true</code> if this site is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this site is status.
	 *
	 * @param status the status of this site
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the created at of this site.
	 *
	 * @return the created at of this site
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this site.
	 *
	 * @param createdAt the created at of this site
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this site.
	 *
	 * @return the updated at of this site
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this site.
	 *
	 * @param updatedAt the updated at of this site
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Site cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}