/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Visite service. Represents a row in the &quot;visites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.df.lonis.ventesservice.model.impl.VisiteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.df.lonis.ventesservice.model.impl.VisiteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Visite
 * @generated
 */
@ProviderType
public interface VisiteModel extends BaseModel<Visite> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visite model instance should use the {@link Visite} interface instead.
	 */

	/**
	 * Returns the primary key of this visite.
	 *
	 * @return the primary key of this visite
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visite.
	 *
	 * @param primaryKey the primary key of this visite
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this visite.
	 *
	 * @return the ID of this visite
	 */
	public long getId();

	/**
	 * Sets the ID of this visite.
	 *
	 * @param id the ID of this visite
	 */
	public void setId(long id);

	/**
	 * Returns the commercial ID of this visite.
	 *
	 * @return the commercial ID of this visite
	 */
	public long getCommercialId();

	/**
	 * Sets the commercial ID of this visite.
	 *
	 * @param commercialId the commercial ID of this visite
	 */
	public void setCommercialId(long commercialId);

	/**
	 * Returns the terminal ID of this visite.
	 *
	 * @return the terminal ID of this visite
	 */
	public long getTerminalId();

	/**
	 * Sets the terminal ID of this visite.
	 *
	 * @param terminalId the terminal ID of this visite
	 */
	public void setTerminalId(long terminalId);

	/**
	 * Returns the latitude of this visite.
	 *
	 * @return the latitude of this visite
	 */
	public Double getLatitude();

	/**
	 * Sets the latitude of this visite.
	 *
	 * @param latitude the latitude of this visite
	 */
	public void setLatitude(Double latitude);

	/**
	 * Returns the longitude of this visite.
	 *
	 * @return the longitude of this visite
	 */
	public Double getLongitude();

	/**
	 * Sets the longitude of this visite.
	 *
	 * @param longitude the longitude of this visite
	 */
	public void setLongitude(Double longitude);

	/**
	 * Returns the statut of this visite.
	 *
	 * @return the statut of this visite
	 */
	@AutoEscape
	public String getStatut();

	/**
	 * Sets the statut of this visite.
	 *
	 * @param statut the statut of this visite
	 */
	public void setStatut(String statut);

	/**
	 * Returns the type controle of this visite.
	 *
	 * @return the type controle of this visite
	 */
	@AutoEscape
	public String getTypeControle();

	/**
	 * Sets the type controle of this visite.
	 *
	 * @param typeControle the type controle of this visite
	 */
	public void setTypeControle(String typeControle);

	/**
	 * Returns the date visite of this visite.
	 *
	 * @return the date visite of this visite
	 */
	public Date getDateVisite();

	/**
	 * Sets the date visite of this visite.
	 *
	 * @param dateVisite the date visite of this visite
	 */
	public void setDateVisite(Date dateVisite);

	/**
	 * Returns the compte rendu of this visite.
	 *
	 * @return the compte rendu of this visite
	 */
	@AutoEscape
	public String getCompteRendu();

	/**
	 * Sets the compte rendu of this visite.
	 *
	 * @param compteRendu the compte rendu of this visite
	 */
	public void setCompteRendu(String compteRendu);

	/**
	 * Returns the created at of this visite.
	 *
	 * @return the created at of this visite
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this visite.
	 *
	 * @param createdAt the created at of this visite
	 */
	public void setCreatedAt(Date createdAt);

	/**
	 * Returns the updated at of this visite.
	 *
	 * @return the updated at of this visite
	 */
	public Date getUpdatedAt();

	/**
	 * Sets the updated at of this visite.
	 *
	 * @param updatedAt the updated at of this visite
	 */
	public void setUpdatedAt(Date updatedAt);

	@Override
	public Visite cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}