/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.ChiffreAffaires;
import com.df.lonis.ventesservice.model.ChiffreAffairesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChiffreAffaires service. Represents a row in the &quot;chiffre_affaires&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChiffreAffairesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiffreAffairesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChiffreAffairesImpl
 * @generated
 */
public class ChiffreAffairesModelImpl
	extends BaseModelImpl<ChiffreAffaires> implements ChiffreAffairesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chiffre affaires model instance should use the <code>ChiffreAffaires</code> interface instead.
	 */
	public static final String TABLE_NAME = "chiffre_affaires";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"terminal_id", Types.BIGINT},
		{"brut", Types.BIGINT}, {"paiement", Types.BIGINT},
		{"annulation", Types.BIGINT}, {"remboursement", Types.BIGINT},
		{"ventes", Types.BIGINT}, {"balance", Types.BIGINT},
		{"deposit", Types.BIGINT}, {"date", Types.TIMESTAMP},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("terminal_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("brut", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("paiement", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("annulation", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remboursement", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ventes", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("balance", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deposit", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table chiffre_affaires (id LONG not null primary key IDENTITY,terminal_id LONG,brut LONG,paiement LONG,annulation LONG,remboursement LONG,ventes LONG,balance LONG,deposit LONG,date DATE null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table chiffre_affaires";

	public static final String ORDER_BY_JPQL =
		" ORDER BY chiffreAffaires.date DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY chiffre_affaires.date DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERMINALID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ChiffreAffairesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChiffreAffaires.class;
	}

	@Override
	public String getModelClassName() {
		return ChiffreAffaires.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChiffreAffaires, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChiffreAffaires, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChiffreAffaires, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ChiffreAffaires)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChiffreAffaires, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChiffreAffaires, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChiffreAffaires)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChiffreAffaires, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChiffreAffaires, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ChiffreAffaires, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ChiffreAffaires, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ChiffreAffaires, Object>>();

			attributeGetterFunctions.put("id", ChiffreAffaires::getId);
			attributeGetterFunctions.put(
				"terminalId", ChiffreAffaires::getTerminalId);
			attributeGetterFunctions.put("brut", ChiffreAffaires::getBrut);
			attributeGetterFunctions.put(
				"paiement", ChiffreAffaires::getPaiement);
			attributeGetterFunctions.put(
				"annulation", ChiffreAffaires::getAnnulation);
			attributeGetterFunctions.put(
				"remboursement", ChiffreAffaires::getRemboursement);
			attributeGetterFunctions.put("ventes", ChiffreAffaires::getVentes);
			attributeGetterFunctions.put(
				"balance", ChiffreAffaires::getBalance);
			attributeGetterFunctions.put(
				"deposit", ChiffreAffaires::getDeposit);
			attributeGetterFunctions.put("date", ChiffreAffaires::getDate);
			attributeGetterFunctions.put(
				"createdAt", ChiffreAffaires::getCreatedAt);
			attributeGetterFunctions.put(
				"updatedAt", ChiffreAffaires::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ChiffreAffaires, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ChiffreAffaires, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ChiffreAffaires, ?>>();

			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<ChiffreAffaires, Long>)ChiffreAffaires::setId);
			attributeSetterBiConsumers.put(
				"terminalId",
				(BiConsumer<ChiffreAffaires, Long>)
					ChiffreAffaires::setTerminalId);
			attributeSetterBiConsumers.put(
				"brut",
				(BiConsumer<ChiffreAffaires, Long>)ChiffreAffaires::setBrut);
			attributeSetterBiConsumers.put(
				"paiement",
				(BiConsumer<ChiffreAffaires, Long>)
					ChiffreAffaires::setPaiement);
			attributeSetterBiConsumers.put(
				"annulation",
				(BiConsumer<ChiffreAffaires, Long>)
					ChiffreAffaires::setAnnulation);
			attributeSetterBiConsumers.put(
				"remboursement",
				(BiConsumer<ChiffreAffaires, Long>)
					ChiffreAffaires::setRemboursement);
			attributeSetterBiConsumers.put(
				"ventes",
				(BiConsumer<ChiffreAffaires, Long>)ChiffreAffaires::setVentes);
			attributeSetterBiConsumers.put(
				"balance",
				(BiConsumer<ChiffreAffaires, Long>)ChiffreAffaires::setBalance);
			attributeSetterBiConsumers.put(
				"deposit",
				(BiConsumer<ChiffreAffaires, Long>)ChiffreAffaires::setDeposit);
			attributeSetterBiConsumers.put(
				"date",
				(BiConsumer<ChiffreAffaires, Date>)ChiffreAffaires::setDate);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<ChiffreAffaires, Date>)
					ChiffreAffaires::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<ChiffreAffaires, Date>)
					ChiffreAffaires::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getTerminalId() {
		return _terminalId;
	}

	@Override
	public void setTerminalId(long terminalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_terminalId = terminalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTerminalId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("terminal_id"));
	}

	@Override
	public long getBrut() {
		return _brut;
	}

	@Override
	public void setBrut(long brut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brut = brut;
	}

	@Override
	public long getPaiement() {
		return _paiement;
	}

	@Override
	public void setPaiement(long paiement) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paiement = paiement;
	}

	@Override
	public long getAnnulation() {
		return _annulation;
	}

	@Override
	public void setAnnulation(long annulation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annulation = annulation;
	}

	@Override
	public long getRemboursement() {
		return _remboursement;
	}

	@Override
	public void setRemboursement(long remboursement) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remboursement = remboursement;
	}

	@Override
	public long getVentes() {
		return _ventes;
	}

	@Override
	public void setVentes(long ventes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ventes = ventes;
	}

	@Override
	public long getBalance() {
		return _balance;
	}

	@Override
	public void setBalance(long balance) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_balance = balance;
	}

	@Override
	public long getDeposit() {
		return _deposit;
	}

	@Override
	public void setDeposit(long deposit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deposit = deposit;
	}

	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_date = date;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDate() {
		return getColumnOriginalValue("date");
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ChiffreAffaires.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChiffreAffaires toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChiffreAffaires>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChiffreAffairesImpl chiffreAffairesImpl = new ChiffreAffairesImpl();

		chiffreAffairesImpl.setId(getId());
		chiffreAffairesImpl.setTerminalId(getTerminalId());
		chiffreAffairesImpl.setBrut(getBrut());
		chiffreAffairesImpl.setPaiement(getPaiement());
		chiffreAffairesImpl.setAnnulation(getAnnulation());
		chiffreAffairesImpl.setRemboursement(getRemboursement());
		chiffreAffairesImpl.setVentes(getVentes());
		chiffreAffairesImpl.setBalance(getBalance());
		chiffreAffairesImpl.setDeposit(getDeposit());
		chiffreAffairesImpl.setDate(getDate());
		chiffreAffairesImpl.setCreatedAt(getCreatedAt());
		chiffreAffairesImpl.setUpdatedAt(getUpdatedAt());

		chiffreAffairesImpl.resetOriginalValues();

		return chiffreAffairesImpl;
	}

	@Override
	public ChiffreAffaires cloneWithOriginalValues() {
		ChiffreAffairesImpl chiffreAffairesImpl = new ChiffreAffairesImpl();

		chiffreAffairesImpl.setId(this.<Long>getColumnOriginalValue("id"));
		chiffreAffairesImpl.setTerminalId(
			this.<Long>getColumnOriginalValue("terminal_id"));
		chiffreAffairesImpl.setBrut(this.<Long>getColumnOriginalValue("brut"));
		chiffreAffairesImpl.setPaiement(
			this.<Long>getColumnOriginalValue("paiement"));
		chiffreAffairesImpl.setAnnulation(
			this.<Long>getColumnOriginalValue("annulation"));
		chiffreAffairesImpl.setRemboursement(
			this.<Long>getColumnOriginalValue("remboursement"));
		chiffreAffairesImpl.setVentes(
			this.<Long>getColumnOriginalValue("ventes"));
		chiffreAffairesImpl.setBalance(
			this.<Long>getColumnOriginalValue("balance"));
		chiffreAffairesImpl.setDeposit(
			this.<Long>getColumnOriginalValue("deposit"));
		chiffreAffairesImpl.setDate(this.<Date>getColumnOriginalValue("date"));
		chiffreAffairesImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		chiffreAffairesImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return chiffreAffairesImpl;
	}

	@Override
	public int compareTo(ChiffreAffaires chiffreAffaires) {
		int value = 0;

		value = DateUtil.compareTo(getDate(), chiffreAffaires.getDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ChiffreAffaires)) {
			return false;
		}

		ChiffreAffaires chiffreAffaires = (ChiffreAffaires)object;

		long primaryKey = chiffreAffaires.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ChiffreAffaires> toCacheModel() {
		ChiffreAffairesCacheModel chiffreAffairesCacheModel =
			new ChiffreAffairesCacheModel();

		chiffreAffairesCacheModel.id = getId();

		chiffreAffairesCacheModel.terminalId = getTerminalId();

		chiffreAffairesCacheModel.brut = getBrut();

		chiffreAffairesCacheModel.paiement = getPaiement();

		chiffreAffairesCacheModel.annulation = getAnnulation();

		chiffreAffairesCacheModel.remboursement = getRemboursement();

		chiffreAffairesCacheModel.ventes = getVentes();

		chiffreAffairesCacheModel.balance = getBalance();

		chiffreAffairesCacheModel.deposit = getDeposit();

		Date date = getDate();

		if (date != null) {
			chiffreAffairesCacheModel.date = date.getTime();
		}
		else {
			chiffreAffairesCacheModel.date = Long.MIN_VALUE;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			chiffreAffairesCacheModel.createdAt = createdAt.getTime();
		}
		else {
			chiffreAffairesCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			chiffreAffairesCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			chiffreAffairesCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return chiffreAffairesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChiffreAffaires, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChiffreAffaires, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChiffreAffaires, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ChiffreAffaires)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChiffreAffaires>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ChiffreAffaires.class, ModelWrapper.class);

	}

	private long _id;
	private long _terminalId;
	private long _brut;
	private long _paiement;
	private long _annulation;
	private long _remboursement;
	private long _ventes;
	private long _balance;
	private long _deposit;
	private Date _date;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ChiffreAffaires, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ChiffreAffaires)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("terminal_id", _terminalId);
		_columnOriginalValues.put("brut", _brut);
		_columnOriginalValues.put("paiement", _paiement);
		_columnOriginalValues.put("annulation", _annulation);
		_columnOriginalValues.put("remboursement", _remboursement);
		_columnOriginalValues.put("ventes", _ventes);
		_columnOriginalValues.put("balance", _balance);
		_columnOriginalValues.put("deposit", _deposit);
		_columnOriginalValues.put("date", _date);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("terminal_id", "terminalId");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("terminal_id", 2L);

		columnBitmasks.put("brut", 4L);

		columnBitmasks.put("paiement", 8L);

		columnBitmasks.put("annulation", 16L);

		columnBitmasks.put("remboursement", 32L);

		columnBitmasks.put("ventes", 64L);

		columnBitmasks.put("balance", 128L);

		columnBitmasks.put("deposit", 256L);

		columnBitmasks.put("date", 512L);

		columnBitmasks.put("created_at", 1024L);

		columnBitmasks.put("updated_at", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ChiffreAffaires _escapedModel;

}