/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.ChiffreAffaires;
import com.df.lonis.ventesservice.service.ChiffreAffairesLocalServiceUtil;

/**
 * The extended model base implementation for the ChiffreAffaires service. Represents a row in the &quot;chiffre_affaires&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiffreAffairesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChiffreAffairesImpl
 * @see ChiffreAffaires
 * @generated
 */
public abstract class ChiffreAffairesBaseImpl
	extends ChiffreAffairesModelImpl implements ChiffreAffaires {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chiffre affaires model instance should use the <code>ChiffreAffaires</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ChiffreAffairesLocalServiceUtil.addChiffreAffaires(this);
		}
		else {
			ChiffreAffairesLocalServiceUtil.updateChiffreAffaires(this);
		}
	}

}