/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Commission;
import com.df.lonis.ventesservice.model.CommissionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Commission service. Represents a row in the &quot;commissions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommissionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommissionImpl
 * @generated
 */
public class CommissionModelImpl
	extends BaseModelImpl<Commission> implements CommissionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commission model instance should use the <code>Commission</code> interface instead.
	 */
	public static final String TABLE_NAME = "commissions";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"code", Types.VARCHAR},
		{"terminal_id", Types.BIGINT}, {"nombre_terminal", Types.INTEGER},
		{"paye", Types.BOOLEAN}, {"libelle", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("terminal_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nombre_terminal", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("paye", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("libelle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table commissions (id LONG not null primary key IDENTITY,code VARCHAR(75) null,terminal_id LONG,nombre_terminal INTEGER,paye BOOLEAN,libelle VARCHAR(75) null,status VARCHAR(75) null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table commissions";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commission.createdAt DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY commissions.created_at DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERMINALID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDAT_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommissionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Commission.class;
	}

	@Override
	public String getModelClassName() {
		return Commission.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Commission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Commission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commission, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Commission)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Commission, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Commission, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Commission)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Commission, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Commission, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Commission, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Commission, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Commission, Object>>();

			attributeGetterFunctions.put("id", Commission::getId);
			attributeGetterFunctions.put("code", Commission::getCode);
			attributeGetterFunctions.put(
				"terminalId", Commission::getTerminalId);
			attributeGetterFunctions.put(
				"nombreTerminal", Commission::getNombreTerminal);
			attributeGetterFunctions.put("paye", Commission::getPaye);
			attributeGetterFunctions.put("libelle", Commission::getLibelle);
			attributeGetterFunctions.put("status", Commission::getStatus);
			attributeGetterFunctions.put("createdAt", Commission::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Commission::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Commission, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Commission, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Commission, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Commission, Long>)Commission::setId);
			attributeSetterBiConsumers.put(
				"code", (BiConsumer<Commission, String>)Commission::setCode);
			attributeSetterBiConsumers.put(
				"terminalId",
				(BiConsumer<Commission, Long>)Commission::setTerminalId);
			attributeSetterBiConsumers.put(
				"nombreTerminal",
				(BiConsumer<Commission, Integer>)Commission::setNombreTerminal);
			attributeSetterBiConsumers.put(
				"paye", (BiConsumer<Commission, Boolean>)Commission::setPaye);
			attributeSetterBiConsumers.put(
				"libelle",
				(BiConsumer<Commission, String>)Commission::setLibelle);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<Commission, String>)Commission::setStatus);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Commission, Date>)Commission::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Commission, Date>)Commission::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	@Override
	public long getTerminalId() {
		return _terminalId;
	}

	@Override
	public void setTerminalId(long terminalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_terminalId = terminalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTerminalId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("terminal_id"));
	}

	@Override
	public int getNombreTerminal() {
		return _nombreTerminal;
	}

	@Override
	public void setNombreTerminal(int nombreTerminal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nombreTerminal = nombreTerminal;
	}

	@Override
	public boolean getPaye() {
		return _paye;
	}

	@Override
	public boolean isPaye() {
		return _paye;
	}

	@Override
	public void setPaye(boolean paye) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paye = paye;
	}

	@Override
	public String getLibelle() {
		if (_libelle == null) {
			return "";
		}
		else {
			return _libelle;
		}
	}

	@Override
	public void setLibelle(String libelle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_libelle = libelle;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Commission.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Commission toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Commission>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommissionImpl commissionImpl = new CommissionImpl();

		commissionImpl.setId(getId());
		commissionImpl.setCode(getCode());
		commissionImpl.setTerminalId(getTerminalId());
		commissionImpl.setNombreTerminal(getNombreTerminal());
		commissionImpl.setPaye(isPaye());
		commissionImpl.setLibelle(getLibelle());
		commissionImpl.setStatus(getStatus());
		commissionImpl.setCreatedAt(getCreatedAt());
		commissionImpl.setUpdatedAt(getUpdatedAt());

		commissionImpl.resetOriginalValues();

		return commissionImpl;
	}

	@Override
	public Commission cloneWithOriginalValues() {
		CommissionImpl commissionImpl = new CommissionImpl();

		commissionImpl.setId(this.<Long>getColumnOriginalValue("id"));
		commissionImpl.setCode(this.<String>getColumnOriginalValue("code"));
		commissionImpl.setTerminalId(
			this.<Long>getColumnOriginalValue("terminal_id"));
		commissionImpl.setNombreTerminal(
			this.<Integer>getColumnOriginalValue("nombre_terminal"));
		commissionImpl.setPaye(this.<Boolean>getColumnOriginalValue("paye"));
		commissionImpl.setLibelle(
			this.<String>getColumnOriginalValue("libelle"));
		commissionImpl.setStatus(this.<String>getColumnOriginalValue("status"));
		commissionImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		commissionImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return commissionImpl;
	}

	@Override
	public int compareTo(Commission commission) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedAt(), commission.getCreatedAt());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Commission)) {
			return false;
		}

		Commission commission = (Commission)object;

		long primaryKey = commission.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Commission> toCacheModel() {
		CommissionCacheModel commissionCacheModel = new CommissionCacheModel();

		commissionCacheModel.id = getId();

		commissionCacheModel.code = getCode();

		String code = commissionCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			commissionCacheModel.code = null;
		}

		commissionCacheModel.terminalId = getTerminalId();

		commissionCacheModel.nombreTerminal = getNombreTerminal();

		commissionCacheModel.paye = isPaye();

		commissionCacheModel.libelle = getLibelle();

		String libelle = commissionCacheModel.libelle;

		if ((libelle != null) && (libelle.length() == 0)) {
			commissionCacheModel.libelle = null;
		}

		commissionCacheModel.status = getStatus();

		String status = commissionCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			commissionCacheModel.status = null;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			commissionCacheModel.createdAt = createdAt.getTime();
		}
		else {
			commissionCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			commissionCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			commissionCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return commissionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Commission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Commission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commission, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Commission)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Commission>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Commission.class, ModelWrapper.class);

	}

	private long _id;
	private String _code;
	private long _terminalId;
	private int _nombreTerminal;
	private boolean _paye;
	private String _libelle;
	private String _status;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Commission, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Commission)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("terminal_id", _terminalId);
		_columnOriginalValues.put("nombre_terminal", _nombreTerminal);
		_columnOriginalValues.put("paye", _paye);
		_columnOriginalValues.put("libelle", _libelle);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("terminal_id", "terminalId");
		attributeNames.put("nombre_terminal", "nombreTerminal");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("code", 2L);

		columnBitmasks.put("terminal_id", 4L);

		columnBitmasks.put("nombre_terminal", 8L);

		columnBitmasks.put("paye", 16L);

		columnBitmasks.put("libelle", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("created_at", 128L);

		columnBitmasks.put("updated_at", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Commission _escapedModel;

}