/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Commercial;
import com.df.lonis.ventesservice.service.CommercialLocalServiceUtil;

/**
 * The extended model base implementation for the Commercial service. Represents a row in the &quot;commerciaux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommercialImpl
 * @see Commercial
 * @generated
 */
public abstract class CommercialBaseImpl
	extends CommercialModelImpl implements Commercial {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commercial model instance should use the <code>Commercial</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommercialLocalServiceUtil.addCommercial(this);
		}
		else {
			CommercialLocalServiceUtil.updateCommercial(this);
		}
	}

}