/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Commercial;
import com.df.lonis.ventesservice.model.CommercialModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Commercial service. Represents a row in the &quot;commerciaux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommercialModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommercialImpl
 * @generated
 */
public class CommercialModelImpl
	extends BaseModelImpl<Commercial> implements CommercialModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commercial model instance should use the <code>Commercial</code> interface instead.
	 */
	public static final String TABLE_NAME = "commerciaux";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"nom", Types.VARCHAR},
		{"prenoms", Types.VARCHAR}, {"telephone", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"matricule", Types.VARCHAR},
		{"statut", Types.VARCHAR}, {"superviseur_id", Types.BIGINT},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prenoms", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telephone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("matricule", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statut", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("superviseur_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table commerciaux (id LONG not null primary key IDENTITY,nom VARCHAR(75) null,prenoms VARCHAR(75) null,telephone VARCHAR(75) null,email VARCHAR(75) null,matricule VARCHAR(75) null,statut VARCHAR(75) null,superviseur_id LONG,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table commerciaux";

	public static final String ORDER_BY_JPQL = " ORDER BY commercial.nom ASC";

	public static final String ORDER_BY_SQL = " ORDER BY commerciaux.nom ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MATRICULE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUT_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUPERVISEURID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOM_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommercialModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Commercial.class;
	}

	@Override
	public String getModelClassName() {
		return Commercial.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Commercial, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Commercial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commercial, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Commercial)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Commercial, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Commercial, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Commercial)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Commercial, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Commercial, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Commercial, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Commercial, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Commercial, Object>>();

			attributeGetterFunctions.put("id", Commercial::getId);
			attributeGetterFunctions.put("nom", Commercial::getNom);
			attributeGetterFunctions.put("prenoms", Commercial::getPrenoms);
			attributeGetterFunctions.put("telephone", Commercial::getTelephone);
			attributeGetterFunctions.put("email", Commercial::getEmail);
			attributeGetterFunctions.put("matricule", Commercial::getMatricule);
			attributeGetterFunctions.put("statut", Commercial::getStatut);
			attributeGetterFunctions.put(
				"superviseurId", Commercial::getSuperviseurId);
			attributeGetterFunctions.put("createdAt", Commercial::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Commercial::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Commercial, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Commercial, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Commercial, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Commercial, Long>)Commercial::setId);
			attributeSetterBiConsumers.put(
				"nom", (BiConsumer<Commercial, String>)Commercial::setNom);
			attributeSetterBiConsumers.put(
				"prenoms",
				(BiConsumer<Commercial, String>)Commercial::setPrenoms);
			attributeSetterBiConsumers.put(
				"telephone",
				(BiConsumer<Commercial, String>)Commercial::setTelephone);
			attributeSetterBiConsumers.put(
				"email", (BiConsumer<Commercial, String>)Commercial::setEmail);
			attributeSetterBiConsumers.put(
				"matricule",
				(BiConsumer<Commercial, String>)Commercial::setMatricule);
			attributeSetterBiConsumers.put(
				"statut",
				(BiConsumer<Commercial, String>)Commercial::setStatut);
			attributeSetterBiConsumers.put(
				"superviseurId",
				(BiConsumer<Commercial, Long>)Commercial::setSuperviseurId);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Commercial, Date>)Commercial::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Commercial, Date>)Commercial::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getNom() {
		if (_nom == null) {
			return "";
		}
		else {
			return _nom;
		}
	}

	@Override
	public void setNom(String nom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nom = nom;
	}

	@Override
	public String getPrenoms() {
		if (_prenoms == null) {
			return "";
		}
		else {
			return _prenoms;
		}
	}

	@Override
	public void setPrenoms(String prenoms) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenoms = prenoms;
	}

	@Override
	public String getTelephone() {
		if (_telephone == null) {
			return "";
		}
		else {
			return _telephone;
		}
	}

	@Override
	public void setTelephone(String telephone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_telephone = telephone;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public String getMatricule() {
		if (_matricule == null) {
			return "";
		}
		else {
			return _matricule;
		}
	}

	@Override
	public void setMatricule(String matricule) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_matricule = matricule;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMatricule() {
		return getColumnOriginalValue("matricule");
	}

	@Override
	public String getStatut() {
		if (_statut == null) {
			return "";
		}
		else {
			return _statut;
		}
	}

	@Override
	public void setStatut(String statut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statut = statut;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatut() {
		return getColumnOriginalValue("statut");
	}

	@Override
	public long getSuperviseurId() {
		return _superviseurId;
	}

	@Override
	public void setSuperviseurId(long superviseurId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_superviseurId = superviseurId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSuperviseurId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("superviseur_id"));
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Commercial.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Commercial toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Commercial>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommercialImpl commercialImpl = new CommercialImpl();

		commercialImpl.setId(getId());
		commercialImpl.setNom(getNom());
		commercialImpl.setPrenoms(getPrenoms());
		commercialImpl.setTelephone(getTelephone());
		commercialImpl.setEmail(getEmail());
		commercialImpl.setMatricule(getMatricule());
		commercialImpl.setStatut(getStatut());
		commercialImpl.setSuperviseurId(getSuperviseurId());
		commercialImpl.setCreatedAt(getCreatedAt());
		commercialImpl.setUpdatedAt(getUpdatedAt());

		commercialImpl.resetOriginalValues();

		return commercialImpl;
	}

	@Override
	public Commercial cloneWithOriginalValues() {
		CommercialImpl commercialImpl = new CommercialImpl();

		commercialImpl.setId(this.<Long>getColumnOriginalValue("id"));
		commercialImpl.setNom(this.<String>getColumnOriginalValue("nom"));
		commercialImpl.setPrenoms(
			this.<String>getColumnOriginalValue("prenoms"));
		commercialImpl.setTelephone(
			this.<String>getColumnOriginalValue("telephone"));
		commercialImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		commercialImpl.setMatricule(
			this.<String>getColumnOriginalValue("matricule"));
		commercialImpl.setStatut(this.<String>getColumnOriginalValue("statut"));
		commercialImpl.setSuperviseurId(
			this.<Long>getColumnOriginalValue("superviseur_id"));
		commercialImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		commercialImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return commercialImpl;
	}

	@Override
	public int compareTo(Commercial commercial) {
		int value = 0;

		value = getNom().compareTo(commercial.getNom());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Commercial)) {
			return false;
		}

		Commercial commercial = (Commercial)object;

		long primaryKey = commercial.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Commercial> toCacheModel() {
		CommercialCacheModel commercialCacheModel = new CommercialCacheModel();

		commercialCacheModel.id = getId();

		commercialCacheModel.nom = getNom();

		String nom = commercialCacheModel.nom;

		if ((nom != null) && (nom.length() == 0)) {
			commercialCacheModel.nom = null;
		}

		commercialCacheModel.prenoms = getPrenoms();

		String prenoms = commercialCacheModel.prenoms;

		if ((prenoms != null) && (prenoms.length() == 0)) {
			commercialCacheModel.prenoms = null;
		}

		commercialCacheModel.telephone = getTelephone();

		String telephone = commercialCacheModel.telephone;

		if ((telephone != null) && (telephone.length() == 0)) {
			commercialCacheModel.telephone = null;
		}

		commercialCacheModel.email = getEmail();

		String email = commercialCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			commercialCacheModel.email = null;
		}

		commercialCacheModel.matricule = getMatricule();

		String matricule = commercialCacheModel.matricule;

		if ((matricule != null) && (matricule.length() == 0)) {
			commercialCacheModel.matricule = null;
		}

		commercialCacheModel.statut = getStatut();

		String statut = commercialCacheModel.statut;

		if ((statut != null) && (statut.length() == 0)) {
			commercialCacheModel.statut = null;
		}

		commercialCacheModel.superviseurId = getSuperviseurId();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			commercialCacheModel.createdAt = createdAt.getTime();
		}
		else {
			commercialCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			commercialCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			commercialCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return commercialCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Commercial, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Commercial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commercial, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Commercial)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Commercial>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Commercial.class, ModelWrapper.class);

	}

	private long _id;
	private String _nom;
	private String _prenoms;
	private String _telephone;
	private String _email;
	private String _matricule;
	private String _statut;
	private long _superviseurId;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Commercial, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Commercial)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("nom", _nom);
		_columnOriginalValues.put("prenoms", _prenoms);
		_columnOriginalValues.put("telephone", _telephone);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("matricule", _matricule);
		_columnOriginalValues.put("statut", _statut);
		_columnOriginalValues.put("superviseur_id", _superviseurId);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("superviseur_id", "superviseurId");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("nom", 2L);

		columnBitmasks.put("prenoms", 4L);

		columnBitmasks.put("telephone", 8L);

		columnBitmasks.put("email", 16L);

		columnBitmasks.put("matricule", 32L);

		columnBitmasks.put("statut", 64L);

		columnBitmasks.put("superviseur_id", 128L);

		columnBitmasks.put("created_at", 256L);

		columnBitmasks.put("updated_at", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Commercial _escapedModel;

}