/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Commission;
import com.df.lonis.ventesservice.service.CommissionLocalServiceUtil;

/**
 * The extended model base implementation for the Commission service. Represents a row in the &quot;commissions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommissionImpl
 * @see Commission
 * @generated
 */
public abstract class CommissionBaseImpl
	extends CommissionModelImpl implements Commission {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commission model instance should use the <code>Commission</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommissionLocalServiceUtil.addCommission(this);
		}
		else {
			CommissionLocalServiceUtil.updateCommission(this);
		}
	}

}