/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Concessionnaire;
import com.df.lonis.ventesservice.model.ConcessionnaireModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Concessionnaire service. Represents a row in the &quot;concessionnaires&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConcessionnaireModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConcessionnaireImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcessionnaireImpl
 * @generated
 */
public class ConcessionnaireModelImpl
	extends BaseModelImpl<Concessionnaire> implements ConcessionnaireModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a concessionnaire model instance should use the <code>Concessionnaire</code> interface instead.
	 */
	public static final String TABLE_NAME = "concessionnaires";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"uid", Types.VARCHAR}, {"nom", Types.VARCHAR},
		{"prenoms", Types.VARCHAR}, {"telephone", Types.VARCHAR},
		{"email", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prenoms", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telephone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table concessionnaires (id LONG not null primary key IDENTITY,uid VARCHAR(75) null,nom VARCHAR(75) null,prenoms VARCHAR(75) null,telephone VARCHAR(75) null,email VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table concessionnaires";

	public static final String ORDER_BY_JPQL =
		" ORDER BY concessionnaire.nom ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY concessionnaires.nom ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOM_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ConcessionnaireModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Concessionnaire.class;
	}

	@Override
	public String getModelClassName() {
		return Concessionnaire.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Concessionnaire, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Concessionnaire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Concessionnaire, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Concessionnaire)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Concessionnaire, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Concessionnaire, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Concessionnaire)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Concessionnaire, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Concessionnaire, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Concessionnaire, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Concessionnaire, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<Concessionnaire, Object>>();

			attributeGetterFunctions.put("id", Concessionnaire::getId);
			attributeGetterFunctions.put("uid", Concessionnaire::getUid);
			attributeGetterFunctions.put("nom", Concessionnaire::getNom);
			attributeGetterFunctions.put(
				"prenoms", Concessionnaire::getPrenoms);
			attributeGetterFunctions.put(
				"telephone", Concessionnaire::getTelephone);
			attributeGetterFunctions.put("email", Concessionnaire::getEmail);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Concessionnaire, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Concessionnaire, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Concessionnaire, ?>>();

			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<Concessionnaire, Long>)Concessionnaire::setId);
			attributeSetterBiConsumers.put(
				"uid",
				(BiConsumer<Concessionnaire, String>)Concessionnaire::setUid);
			attributeSetterBiConsumers.put(
				"nom",
				(BiConsumer<Concessionnaire, String>)Concessionnaire::setNom);
			attributeSetterBiConsumers.put(
				"prenoms",
				(BiConsumer<Concessionnaire, String>)
					Concessionnaire::setPrenoms);
			attributeSetterBiConsumers.put(
				"telephone",
				(BiConsumer<Concessionnaire, String>)
					Concessionnaire::setTelephone);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<Concessionnaire, String>)Concessionnaire::setEmail);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getUid() {
		if (_uid == null) {
			return "";
		}
		else {
			return _uid;
		}
	}

	@Override
	public void setUid(String uid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uid = uid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUid() {
		return getColumnOriginalValue("uid");
	}

	@Override
	public String getNom() {
		if (_nom == null) {
			return "";
		}
		else {
			return _nom;
		}
	}

	@Override
	public void setNom(String nom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nom = nom;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNom() {
		return getColumnOriginalValue("nom");
	}

	@Override
	public String getPrenoms() {
		if (_prenoms == null) {
			return "";
		}
		else {
			return _prenoms;
		}
	}

	@Override
	public void setPrenoms(String prenoms) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenoms = prenoms;
	}

	@Override
	public String getTelephone() {
		if (_telephone == null) {
			return "";
		}
		else {
			return _telephone;
		}
	}

	@Override
	public void setTelephone(String telephone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_telephone = telephone;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Concessionnaire.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Concessionnaire toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Concessionnaire>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConcessionnaireImpl concessionnaireImpl = new ConcessionnaireImpl();

		concessionnaireImpl.setId(getId());
		concessionnaireImpl.setUid(getUid());
		concessionnaireImpl.setNom(getNom());
		concessionnaireImpl.setPrenoms(getPrenoms());
		concessionnaireImpl.setTelephone(getTelephone());
		concessionnaireImpl.setEmail(getEmail());

		concessionnaireImpl.resetOriginalValues();

		return concessionnaireImpl;
	}

	@Override
	public Concessionnaire cloneWithOriginalValues() {
		ConcessionnaireImpl concessionnaireImpl = new ConcessionnaireImpl();

		concessionnaireImpl.setId(this.<Long>getColumnOriginalValue("id"));
		concessionnaireImpl.setUid(this.<String>getColumnOriginalValue("uid"));
		concessionnaireImpl.setNom(this.<String>getColumnOriginalValue("nom"));
		concessionnaireImpl.setPrenoms(
			this.<String>getColumnOriginalValue("prenoms"));
		concessionnaireImpl.setTelephone(
			this.<String>getColumnOriginalValue("telephone"));
		concessionnaireImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));

		return concessionnaireImpl;
	}

	@Override
	public int compareTo(Concessionnaire concessionnaire) {
		int value = 0;

		value = getNom().compareTo(concessionnaire.getNom());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Concessionnaire)) {
			return false;
		}

		Concessionnaire concessionnaire = (Concessionnaire)object;

		long primaryKey = concessionnaire.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Concessionnaire> toCacheModel() {
		ConcessionnaireCacheModel concessionnaireCacheModel =
			new ConcessionnaireCacheModel();

		concessionnaireCacheModel.id = getId();

		concessionnaireCacheModel.uid = getUid();

		String uid = concessionnaireCacheModel.uid;

		if ((uid != null) && (uid.length() == 0)) {
			concessionnaireCacheModel.uid = null;
		}

		concessionnaireCacheModel.nom = getNom();

		String nom = concessionnaireCacheModel.nom;

		if ((nom != null) && (nom.length() == 0)) {
			concessionnaireCacheModel.nom = null;
		}

		concessionnaireCacheModel.prenoms = getPrenoms();

		String prenoms = concessionnaireCacheModel.prenoms;

		if ((prenoms != null) && (prenoms.length() == 0)) {
			concessionnaireCacheModel.prenoms = null;
		}

		concessionnaireCacheModel.telephone = getTelephone();

		String telephone = concessionnaireCacheModel.telephone;

		if ((telephone != null) && (telephone.length() == 0)) {
			concessionnaireCacheModel.telephone = null;
		}

		concessionnaireCacheModel.email = getEmail();

		String email = concessionnaireCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			concessionnaireCacheModel.email = null;
		}

		return concessionnaireCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Concessionnaire, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Concessionnaire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Concessionnaire, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Concessionnaire)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Concessionnaire>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Concessionnaire.class, ModelWrapper.class);

	}

	private long _id;
	private String _uid;
	private String _nom;
	private String _prenoms;
	private String _telephone;
	private String _email;

	public <T> T getColumnValue(String columnName) {
		Function<Concessionnaire, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Concessionnaire)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("uid", _uid);
		_columnOriginalValues.put("nom", _nom);
		_columnOriginalValues.put("prenoms", _prenoms);
		_columnOriginalValues.put("telephone", _telephone);
		_columnOriginalValues.put("email", _email);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("uid", 2L);

		columnBitmasks.put("nom", 4L);

		columnBitmasks.put("prenoms", 8L);

		columnBitmasks.put("telephone", 16L);

		columnBitmasks.put("email", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Concessionnaire _escapedModel;

}