/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.ConcessionnaireProduit;
import com.df.lonis.ventesservice.model.ConcessionnaireProduitModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ConcessionnaireProduit service. Represents a row in the &quot;concessionnaire_produit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConcessionnaireProduitModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConcessionnaireProduitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcessionnaireProduitImpl
 * @generated
 */
public class ConcessionnaireProduitModelImpl
	extends BaseModelImpl<ConcessionnaireProduit>
	implements ConcessionnaireProduitModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a concessionnaire produit model instance should use the <code>ConcessionnaireProduit</code> interface instead.
	 */
	public static final String TABLE_NAME = "concessionnaire_produit";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"concessionnaire_id", Types.BIGINT},
		{"produit_id", Types.BIGINT}, {"site_id", Types.BIGINT},
		{"code", Types.VARCHAR}, {"concessionnaire_code", Types.VARCHAR},
		{"active", Types.BOOLEAN}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("concessionnaire_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("produit_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("site_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("concessionnaire_code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table concessionnaire_produit (id LONG not null primary key IDENTITY,concessionnaire_id LONG,produit_id LONG,site_id LONG,code VARCHAR(75) null,concessionnaire_code VARCHAR(75) null,active BOOLEAN,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table concessionnaire_produit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY concessionnaireProduit.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY concessionnaire_produit.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONCESSIONNAIREID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUITID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ConcessionnaireProduitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConcessionnaireProduit.class;
	}

	@Override
	public String getModelClassName() {
		return ConcessionnaireProduit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConcessionnaireProduit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConcessionnaireProduit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcessionnaireProduit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConcessionnaireProduit)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConcessionnaireProduit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConcessionnaireProduit, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConcessionnaireProduit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConcessionnaireProduit, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConcessionnaireProduit, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<ConcessionnaireProduit, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<ConcessionnaireProduit, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ConcessionnaireProduit, Object>>();

			attributeGetterFunctions.put("id", ConcessionnaireProduit::getId);
			attributeGetterFunctions.put(
				"concessionnaireId",
				ConcessionnaireProduit::getConcessionnaireId);
			attributeGetterFunctions.put(
				"produitId", ConcessionnaireProduit::getProduitId);
			attributeGetterFunctions.put(
				"siteId", ConcessionnaireProduit::getSiteId);
			attributeGetterFunctions.put(
				"code", ConcessionnaireProduit::getCode);
			attributeGetterFunctions.put(
				"concessionnaireCode",
				ConcessionnaireProduit::getConcessionnaireCode);
			attributeGetterFunctions.put(
				"active", ConcessionnaireProduit::getActive);
			attributeGetterFunctions.put(
				"createdAt", ConcessionnaireProduit::getCreatedAt);
			attributeGetterFunctions.put(
				"updatedAt", ConcessionnaireProduit::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ConcessionnaireProduit, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ConcessionnaireProduit, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ConcessionnaireProduit, ?>>();

			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<ConcessionnaireProduit, Long>)
					ConcessionnaireProduit::setId);
			attributeSetterBiConsumers.put(
				"concessionnaireId",
				(BiConsumer<ConcessionnaireProduit, Long>)
					ConcessionnaireProduit::setConcessionnaireId);
			attributeSetterBiConsumers.put(
				"produitId",
				(BiConsumer<ConcessionnaireProduit, Long>)
					ConcessionnaireProduit::setProduitId);
			attributeSetterBiConsumers.put(
				"siteId",
				(BiConsumer<ConcessionnaireProduit, Long>)
					ConcessionnaireProduit::setSiteId);
			attributeSetterBiConsumers.put(
				"code",
				(BiConsumer<ConcessionnaireProduit, String>)
					ConcessionnaireProduit::setCode);
			attributeSetterBiConsumers.put(
				"concessionnaireCode",
				(BiConsumer<ConcessionnaireProduit, String>)
					ConcessionnaireProduit::setConcessionnaireCode);
			attributeSetterBiConsumers.put(
				"active",
				(BiConsumer<ConcessionnaireProduit, Boolean>)
					ConcessionnaireProduit::setActive);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<ConcessionnaireProduit, Date>)
					ConcessionnaireProduit::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<ConcessionnaireProduit, Date>)
					ConcessionnaireProduit::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getConcessionnaireId() {
		return _concessionnaireId;
	}

	@Override
	public void setConcessionnaireId(long concessionnaireId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessionnaireId = concessionnaireId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalConcessionnaireId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("concessionnaire_id"));
	}

	@Override
	public long getProduitId() {
		return _produitId;
	}

	@Override
	public void setProduitId(long produitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_produitId = produitId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProduitId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("produit_id"));
	}

	@Override
	public long getSiteId() {
		return _siteId;
	}

	@Override
	public void setSiteId(long siteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_siteId = siteId;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code");
	}

	@Override
	public String getConcessionnaireCode() {
		if (_concessionnaireCode == null) {
			return "";
		}
		else {
			return _concessionnaireCode;
		}
	}

	@Override
	public void setConcessionnaireCode(String concessionnaireCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessionnaireCode = concessionnaireCode;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ConcessionnaireProduit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConcessionnaireProduit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ConcessionnaireProduit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConcessionnaireProduitImpl concessionnaireProduitImpl =
			new ConcessionnaireProduitImpl();

		concessionnaireProduitImpl.setId(getId());
		concessionnaireProduitImpl.setConcessionnaireId(getConcessionnaireId());
		concessionnaireProduitImpl.setProduitId(getProduitId());
		concessionnaireProduitImpl.setSiteId(getSiteId());
		concessionnaireProduitImpl.setCode(getCode());
		concessionnaireProduitImpl.setConcessionnaireCode(
			getConcessionnaireCode());
		concessionnaireProduitImpl.setActive(isActive());
		concessionnaireProduitImpl.setCreatedAt(getCreatedAt());
		concessionnaireProduitImpl.setUpdatedAt(getUpdatedAt());

		concessionnaireProduitImpl.resetOriginalValues();

		return concessionnaireProduitImpl;
	}

	@Override
	public ConcessionnaireProduit cloneWithOriginalValues() {
		ConcessionnaireProduitImpl concessionnaireProduitImpl =
			new ConcessionnaireProduitImpl();

		concessionnaireProduitImpl.setId(
			this.<Long>getColumnOriginalValue("id"));
		concessionnaireProduitImpl.setConcessionnaireId(
			this.<Long>getColumnOriginalValue("concessionnaire_id"));
		concessionnaireProduitImpl.setProduitId(
			this.<Long>getColumnOriginalValue("produit_id"));
		concessionnaireProduitImpl.setSiteId(
			this.<Long>getColumnOriginalValue("site_id"));
		concessionnaireProduitImpl.setCode(
			this.<String>getColumnOriginalValue("code"));
		concessionnaireProduitImpl.setConcessionnaireCode(
			this.<String>getColumnOriginalValue("concessionnaire_code"));
		concessionnaireProduitImpl.setActive(
			this.<Boolean>getColumnOriginalValue("active"));
		concessionnaireProduitImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		concessionnaireProduitImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return concessionnaireProduitImpl;
	}

	@Override
	public int compareTo(ConcessionnaireProduit concessionnaireProduit) {
		long primaryKey = concessionnaireProduit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ConcessionnaireProduit)) {
			return false;
		}

		ConcessionnaireProduit concessionnaireProduit =
			(ConcessionnaireProduit)object;

		long primaryKey = concessionnaireProduit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ConcessionnaireProduit> toCacheModel() {
		ConcessionnaireProduitCacheModel concessionnaireProduitCacheModel =
			new ConcessionnaireProduitCacheModel();

		concessionnaireProduitCacheModel.id = getId();

		concessionnaireProduitCacheModel.concessionnaireId =
			getConcessionnaireId();

		concessionnaireProduitCacheModel.produitId = getProduitId();

		concessionnaireProduitCacheModel.siteId = getSiteId();

		concessionnaireProduitCacheModel.code = getCode();

		String code = concessionnaireProduitCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			concessionnaireProduitCacheModel.code = null;
		}

		concessionnaireProduitCacheModel.concessionnaireCode =
			getConcessionnaireCode();

		String concessionnaireCode =
			concessionnaireProduitCacheModel.concessionnaireCode;

		if ((concessionnaireCode != null) &&
			(concessionnaireCode.length() == 0)) {

			concessionnaireProduitCacheModel.concessionnaireCode = null;
		}

		concessionnaireProduitCacheModel.active = isActive();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			concessionnaireProduitCacheModel.createdAt = createdAt.getTime();
		}
		else {
			concessionnaireProduitCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			concessionnaireProduitCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			concessionnaireProduitCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return concessionnaireProduitCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConcessionnaireProduit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConcessionnaireProduit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcessionnaireProduit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ConcessionnaireProduit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ConcessionnaireProduit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ConcessionnaireProduit.class, ModelWrapper.class);

	}

	private long _id;
	private long _concessionnaireId;
	private long _produitId;
	private long _siteId;
	private String _code;
	private String _concessionnaireCode;
	private boolean _active;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ConcessionnaireProduit, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ConcessionnaireProduit)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("concessionnaire_id", _concessionnaireId);
		_columnOriginalValues.put("produit_id", _produitId);
		_columnOriginalValues.put("site_id", _siteId);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("concessionnaire_code", _concessionnaireCode);
		_columnOriginalValues.put("active", _active);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("concessionnaire_id", "concessionnaireId");
		attributeNames.put("produit_id", "produitId");
		attributeNames.put("site_id", "siteId");
		attributeNames.put("concessionnaire_code", "concessionnaireCode");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("concessionnaire_id", 2L);

		columnBitmasks.put("produit_id", 4L);

		columnBitmasks.put("site_id", 8L);

		columnBitmasks.put("code", 16L);

		columnBitmasks.put("concessionnaire_code", 32L);

		columnBitmasks.put("active", 64L);

		columnBitmasks.put("created_at", 128L);

		columnBitmasks.put("updated_at", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ConcessionnaireProduit _escapedModel;

}