/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.ConcessionnaireProduit;
import com.df.lonis.ventesservice.service.ConcessionnaireProduitLocalServiceUtil;

/**
 * The extended model base implementation for the ConcessionnaireProduit service. Represents a row in the &quot;concessionnaire_produit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConcessionnaireProduitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcessionnaireProduitImpl
 * @see ConcessionnaireProduit
 * @generated
 */
public abstract class ConcessionnaireProduitBaseImpl
	extends ConcessionnaireProduitModelImpl implements ConcessionnaireProduit {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a concessionnaire produit model instance should use the <code>ConcessionnaireProduit</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ConcessionnaireProduitLocalServiceUtil.addConcessionnaireProduit(
				this);
		}
		else {
			ConcessionnaireProduitLocalServiceUtil.updateConcessionnaireProduit(
				this);
		}
	}

}