/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Evaluation;
import com.df.lonis.ventesservice.model.EvaluationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Evaluation service. Represents a row in the &quot;evaluations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EvaluationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EvaluationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EvaluationImpl
 * @generated
 */
public class EvaluationModelImpl
	extends BaseModelImpl<Evaluation> implements EvaluationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evaluation model instance should use the <code>Evaluation</code> interface instead.
	 */
	public static final String TABLE_NAME = "evaluations";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"commercial_id", Types.BIGINT},
		{"nb_visites_prevues", Types.INTEGER},
		{"nb_visites_effectuees", Types.INTEGER},
		{"taux_realisation", Types.DOUBLE}, {"rang", Types.INTEGER},
		{"periode", Types.VARCHAR}, {"mois", Types.INTEGER},
		{"trimestre", Types.INTEGER}, {"annee", Types.INTEGER},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercial_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nb_visites_prevues", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nb_visites_effectuees", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("taux_realisation", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("rang", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mois", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("trimestre", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("annee", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table evaluations (id LONG not null primary key IDENTITY,commercial_id LONG,nb_visites_prevues INTEGER,nb_visites_effectuees INTEGER,taux_realisation DOUBLE,rang INTEGER,periode VARCHAR(75) null,mois INTEGER,trimestre INTEGER,annee INTEGER,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table evaluations";

	public static final String ORDER_BY_JPQL =
		" ORDER BY evaluation.annee DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY evaluations.annee DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ANNEE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCIALID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOIS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERIODE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EvaluationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Evaluation.class;
	}

	@Override
	public String getModelClassName() {
		return Evaluation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Evaluation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Evaluation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Evaluation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Evaluation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Evaluation, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Evaluation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Evaluation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Evaluation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Evaluation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Evaluation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Evaluation, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Evaluation, Object>>();

			attributeGetterFunctions.put("id", Evaluation::getId);
			attributeGetterFunctions.put(
				"commercialId", Evaluation::getCommercialId);
			attributeGetterFunctions.put(
				"nbVisitesPrevues", Evaluation::getNbVisitesPrevues);
			attributeGetterFunctions.put(
				"nbVisitesEffectuees", Evaluation::getNbVisitesEffectuees);
			attributeGetterFunctions.put(
				"tauxRealisation", Evaluation::getTauxRealisation);
			attributeGetterFunctions.put("rang", Evaluation::getRang);
			attributeGetterFunctions.put("periode", Evaluation::getPeriode);
			attributeGetterFunctions.put("mois", Evaluation::getMois);
			attributeGetterFunctions.put("trimestre", Evaluation::getTrimestre);
			attributeGetterFunctions.put("annee", Evaluation::getAnnee);
			attributeGetterFunctions.put("createdAt", Evaluation::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Evaluation::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Evaluation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Evaluation, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Evaluation, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Evaluation, Long>)Evaluation::setId);
			attributeSetterBiConsumers.put(
				"commercialId",
				(BiConsumer<Evaluation, Long>)Evaluation::setCommercialId);
			attributeSetterBiConsumers.put(
				"nbVisitesPrevues",
				(BiConsumer<Evaluation, Integer>)
					Evaluation::setNbVisitesPrevues);
			attributeSetterBiConsumers.put(
				"nbVisitesEffectuees",
				(BiConsumer<Evaluation, Integer>)
					Evaluation::setNbVisitesEffectuees);
			attributeSetterBiConsumers.put(
				"tauxRealisation",
				(BiConsumer<Evaluation, Double>)Evaluation::setTauxRealisation);
			attributeSetterBiConsumers.put(
				"rang", (BiConsumer<Evaluation, Integer>)Evaluation::setRang);
			attributeSetterBiConsumers.put(
				"periode",
				(BiConsumer<Evaluation, String>)Evaluation::setPeriode);
			attributeSetterBiConsumers.put(
				"mois", (BiConsumer<Evaluation, Integer>)Evaluation::setMois);
			attributeSetterBiConsumers.put(
				"trimestre",
				(BiConsumer<Evaluation, Integer>)Evaluation::setTrimestre);
			attributeSetterBiConsumers.put(
				"annee", (BiConsumer<Evaluation, Integer>)Evaluation::setAnnee);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Evaluation, Date>)Evaluation::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Evaluation, Date>)Evaluation::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCommercialId() {
		return _commercialId;
	}

	@Override
	public void setCommercialId(long commercialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialId = commercialId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommercialId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commercial_id"));
	}

	@Override
	public int getNbVisitesPrevues() {
		return _nbVisitesPrevues;
	}

	@Override
	public void setNbVisitesPrevues(int nbVisitesPrevues) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nbVisitesPrevues = nbVisitesPrevues;
	}

	@Override
	public int getNbVisitesEffectuees() {
		return _nbVisitesEffectuees;
	}

	@Override
	public void setNbVisitesEffectuees(int nbVisitesEffectuees) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nbVisitesEffectuees = nbVisitesEffectuees;
	}

	@Override
	public double getTauxRealisation() {
		return _tauxRealisation;
	}

	@Override
	public void setTauxRealisation(double tauxRealisation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tauxRealisation = tauxRealisation;
	}

	@Override
	public int getRang() {
		return _rang;
	}

	@Override
	public void setRang(int rang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rang = rang;
	}

	@Override
	public String getPeriode() {
		if (_periode == null) {
			return "";
		}
		else {
			return _periode;
		}
	}

	@Override
	public void setPeriode(String periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_periode = periode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPeriode() {
		return getColumnOriginalValue("periode");
	}

	@Override
	public int getMois() {
		return _mois;
	}

	@Override
	public void setMois(int mois) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mois = mois;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalMois() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("mois"));
	}

	@Override
	public int getTrimestre() {
		return _trimestre;
	}

	@Override
	public void setTrimestre(int trimestre) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trimestre = trimestre;
	}

	@Override
	public int getAnnee() {
		return _annee;
	}

	@Override
	public void setAnnee(int annee) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annee = annee;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalAnnee() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("annee"));
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Evaluation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Evaluation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Evaluation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EvaluationImpl evaluationImpl = new EvaluationImpl();

		evaluationImpl.setId(getId());
		evaluationImpl.setCommercialId(getCommercialId());
		evaluationImpl.setNbVisitesPrevues(getNbVisitesPrevues());
		evaluationImpl.setNbVisitesEffectuees(getNbVisitesEffectuees());
		evaluationImpl.setTauxRealisation(getTauxRealisation());
		evaluationImpl.setRang(getRang());
		evaluationImpl.setPeriode(getPeriode());
		evaluationImpl.setMois(getMois());
		evaluationImpl.setTrimestre(getTrimestre());
		evaluationImpl.setAnnee(getAnnee());
		evaluationImpl.setCreatedAt(getCreatedAt());
		evaluationImpl.setUpdatedAt(getUpdatedAt());

		evaluationImpl.resetOriginalValues();

		return evaluationImpl;
	}

	@Override
	public Evaluation cloneWithOriginalValues() {
		EvaluationImpl evaluationImpl = new EvaluationImpl();

		evaluationImpl.setId(this.<Long>getColumnOriginalValue("id"));
		evaluationImpl.setCommercialId(
			this.<Long>getColumnOriginalValue("commercial_id"));
		evaluationImpl.setNbVisitesPrevues(
			this.<Integer>getColumnOriginalValue("nb_visites_prevues"));
		evaluationImpl.setNbVisitesEffectuees(
			this.<Integer>getColumnOriginalValue("nb_visites_effectuees"));
		evaluationImpl.setTauxRealisation(
			this.<Double>getColumnOriginalValue("taux_realisation"));
		evaluationImpl.setRang(this.<Integer>getColumnOriginalValue("rang"));
		evaluationImpl.setPeriode(
			this.<String>getColumnOriginalValue("periode"));
		evaluationImpl.setMois(this.<Integer>getColumnOriginalValue("mois"));
		evaluationImpl.setTrimestre(
			this.<Integer>getColumnOriginalValue("trimestre"));
		evaluationImpl.setAnnee(this.<Integer>getColumnOriginalValue("annee"));
		evaluationImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		evaluationImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return evaluationImpl;
	}

	@Override
	public int compareTo(Evaluation evaluation) {
		int value = 0;

		if (getAnnee() < evaluation.getAnnee()) {
			value = -1;
		}
		else if (getAnnee() > evaluation.getAnnee()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Evaluation)) {
			return false;
		}

		Evaluation evaluation = (Evaluation)object;

		long primaryKey = evaluation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Evaluation> toCacheModel() {
		EvaluationCacheModel evaluationCacheModel = new EvaluationCacheModel();

		evaluationCacheModel.id = getId();

		evaluationCacheModel.commercialId = getCommercialId();

		evaluationCacheModel.nbVisitesPrevues = getNbVisitesPrevues();

		evaluationCacheModel.nbVisitesEffectuees = getNbVisitesEffectuees();

		evaluationCacheModel.tauxRealisation = getTauxRealisation();

		evaluationCacheModel.rang = getRang();

		evaluationCacheModel.periode = getPeriode();

		String periode = evaluationCacheModel.periode;

		if ((periode != null) && (periode.length() == 0)) {
			evaluationCacheModel.periode = null;
		}

		evaluationCacheModel.mois = getMois();

		evaluationCacheModel.trimestre = getTrimestre();

		evaluationCacheModel.annee = getAnnee();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			evaluationCacheModel.createdAt = createdAt.getTime();
		}
		else {
			evaluationCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			evaluationCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			evaluationCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return evaluationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Evaluation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Evaluation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Evaluation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Evaluation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Evaluation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Evaluation.class, ModelWrapper.class);

	}

	private long _id;
	private long _commercialId;
	private int _nbVisitesPrevues;
	private int _nbVisitesEffectuees;
	private double _tauxRealisation;
	private int _rang;
	private String _periode;
	private int _mois;
	private int _trimestre;
	private int _annee;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Evaluation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Evaluation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("commercial_id", _commercialId);
		_columnOriginalValues.put("nb_visites_prevues", _nbVisitesPrevues);
		_columnOriginalValues.put(
			"nb_visites_effectuees", _nbVisitesEffectuees);
		_columnOriginalValues.put("taux_realisation", _tauxRealisation);
		_columnOriginalValues.put("rang", _rang);
		_columnOriginalValues.put("periode", _periode);
		_columnOriginalValues.put("mois", _mois);
		_columnOriginalValues.put("trimestre", _trimestre);
		_columnOriginalValues.put("annee", _annee);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("commercial_id", "commercialId");
		attributeNames.put("nb_visites_prevues", "nbVisitesPrevues");
		attributeNames.put("nb_visites_effectuees", "nbVisitesEffectuees");
		attributeNames.put("taux_realisation", "tauxRealisation");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("commercial_id", 2L);

		columnBitmasks.put("nb_visites_prevues", 4L);

		columnBitmasks.put("nb_visites_effectuees", 8L);

		columnBitmasks.put("taux_realisation", 16L);

		columnBitmasks.put("rang", 32L);

		columnBitmasks.put("periode", 64L);

		columnBitmasks.put("mois", 128L);

		columnBitmasks.put("trimestre", 256L);

		columnBitmasks.put("annee", 512L);

		columnBitmasks.put("created_at", 1024L);

		columnBitmasks.put("updated_at", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Evaluation _escapedModel;

}