/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Objectif;
import com.df.lonis.ventesservice.service.ObjectifLocalServiceUtil;

/**
 * The extended model base implementation for the Objectif service. Represents a row in the &quot;objectifs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectifImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ObjectifImpl
 * @see Objectif
 * @generated
 */
public abstract class ObjectifBaseImpl
	extends ObjectifModelImpl implements Objectif {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a objectif model instance should use the <code>Objectif</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ObjectifLocalServiceUtil.addObjectif(this);
		}
		else {
			ObjectifLocalServiceUtil.updateObjectif(this);
		}
	}

}