/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Objectif;
import com.df.lonis.ventesservice.model.ObjectifModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Objectif service. Represents a row in the &quot;objectifs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ObjectifModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectifImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ObjectifImpl
 * @generated
 */
public class ObjectifModelImpl
	extends BaseModelImpl<Objectif> implements ObjectifModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a objectif model instance should use the <code>Objectif</code> interface instead.
	 */
	public static final String TABLE_NAME = "objectifs";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"commercial_id", Types.BIGINT},
		{"type", Types.VARCHAR}, {"periode", Types.VARCHAR},
		{"valeur_cible", Types.INTEGER}, {"valeur_reelle", Types.INTEGER},
		{"mois", Types.INTEGER}, {"trimestre", Types.INTEGER},
		{"annee", Types.INTEGER}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercial_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valeur_cible", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("valeur_reelle", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("mois", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("trimestre", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("annee", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table objectifs (id LONG not null primary key IDENTITY,commercial_id LONG,type VARCHAR(75) null,periode VARCHAR(75) null,valeur_cible INTEGER,valeur_reelle INTEGER,mois INTEGER,trimestre INTEGER,annee INTEGER,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table objectifs";

	public static final String ORDER_BY_JPQL = " ORDER BY objectif.annee DESC";

	public static final String ORDER_BY_SQL = " ORDER BY objectifs.annee DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ANNEE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCIALID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOIS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ObjectifModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Objectif.class;
	}

	@Override
	public String getModelClassName() {
		return Objectif.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Objectif, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Objectif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Objectif, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Objectif)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Objectif, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Objectif, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Objectif)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Objectif, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Objectif, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Objectif, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Objectif, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Objectif, Object>>();

			attributeGetterFunctions.put("id", Objectif::getId);
			attributeGetterFunctions.put(
				"commercialId", Objectif::getCommercialId);
			attributeGetterFunctions.put("type", Objectif::getType);
			attributeGetterFunctions.put("periode", Objectif::getPeriode);
			attributeGetterFunctions.put(
				"valeurCible", Objectif::getValeurCible);
			attributeGetterFunctions.put(
				"valeurReelle", Objectif::getValeurReelle);
			attributeGetterFunctions.put("mois", Objectif::getMois);
			attributeGetterFunctions.put("trimestre", Objectif::getTrimestre);
			attributeGetterFunctions.put("annee", Objectif::getAnnee);
			attributeGetterFunctions.put("createdAt", Objectif::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Objectif::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Objectif, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Objectif, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Objectif, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Objectif, Long>)Objectif::setId);
			attributeSetterBiConsumers.put(
				"commercialId",
				(BiConsumer<Objectif, Long>)Objectif::setCommercialId);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<Objectif, String>)Objectif::setType);
			attributeSetterBiConsumers.put(
				"periode", (BiConsumer<Objectif, String>)Objectif::setPeriode);
			attributeSetterBiConsumers.put(
				"valeurCible",
				(BiConsumer<Objectif, Integer>)Objectif::setValeurCible);
			attributeSetterBiConsumers.put(
				"valeurReelle",
				(BiConsumer<Objectif, Integer>)Objectif::setValeurReelle);
			attributeSetterBiConsumers.put(
				"mois", (BiConsumer<Objectif, Integer>)Objectif::setMois);
			attributeSetterBiConsumers.put(
				"trimestre",
				(BiConsumer<Objectif, Integer>)Objectif::setTrimestre);
			attributeSetterBiConsumers.put(
				"annee", (BiConsumer<Objectif, Integer>)Objectif::setAnnee);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Objectif, Date>)Objectif::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Objectif, Date>)Objectif::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCommercialId() {
		return _commercialId;
	}

	@Override
	public void setCommercialId(long commercialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialId = commercialId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommercialId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commercial_id"));
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public String getPeriode() {
		if (_periode == null) {
			return "";
		}
		else {
			return _periode;
		}
	}

	@Override
	public void setPeriode(String periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_periode = periode;
	}

	@Override
	public int getValeurCible() {
		return _valeurCible;
	}

	@Override
	public void setValeurCible(int valeurCible) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valeurCible = valeurCible;
	}

	@Override
	public int getValeurReelle() {
		return _valeurReelle;
	}

	@Override
	public void setValeurReelle(int valeurReelle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valeurReelle = valeurReelle;
	}

	@Override
	public int getMois() {
		return _mois;
	}

	@Override
	public void setMois(int mois) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mois = mois;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalMois() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("mois"));
	}

	@Override
	public int getTrimestre() {
		return _trimestre;
	}

	@Override
	public void setTrimestre(int trimestre) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trimestre = trimestre;
	}

	@Override
	public int getAnnee() {
		return _annee;
	}

	@Override
	public void setAnnee(int annee) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annee = annee;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalAnnee() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("annee"));
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Objectif.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Objectif toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Objectif>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ObjectifImpl objectifImpl = new ObjectifImpl();

		objectifImpl.setId(getId());
		objectifImpl.setCommercialId(getCommercialId());
		objectifImpl.setType(getType());
		objectifImpl.setPeriode(getPeriode());
		objectifImpl.setValeurCible(getValeurCible());
		objectifImpl.setValeurReelle(getValeurReelle());
		objectifImpl.setMois(getMois());
		objectifImpl.setTrimestre(getTrimestre());
		objectifImpl.setAnnee(getAnnee());
		objectifImpl.setCreatedAt(getCreatedAt());
		objectifImpl.setUpdatedAt(getUpdatedAt());

		objectifImpl.resetOriginalValues();

		return objectifImpl;
	}

	@Override
	public Objectif cloneWithOriginalValues() {
		ObjectifImpl objectifImpl = new ObjectifImpl();

		objectifImpl.setId(this.<Long>getColumnOriginalValue("id"));
		objectifImpl.setCommercialId(
			this.<Long>getColumnOriginalValue("commercial_id"));
		objectifImpl.setType(this.<String>getColumnOriginalValue("type"));
		objectifImpl.setPeriode(this.<String>getColumnOriginalValue("periode"));
		objectifImpl.setValeurCible(
			this.<Integer>getColumnOriginalValue("valeur_cible"));
		objectifImpl.setValeurReelle(
			this.<Integer>getColumnOriginalValue("valeur_reelle"));
		objectifImpl.setMois(this.<Integer>getColumnOriginalValue("mois"));
		objectifImpl.setTrimestre(
			this.<Integer>getColumnOriginalValue("trimestre"));
		objectifImpl.setAnnee(this.<Integer>getColumnOriginalValue("annee"));
		objectifImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		objectifImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return objectifImpl;
	}

	@Override
	public int compareTo(Objectif objectif) {
		int value = 0;

		if (getAnnee() < objectif.getAnnee()) {
			value = -1;
		}
		else if (getAnnee() > objectif.getAnnee()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Objectif)) {
			return false;
		}

		Objectif objectif = (Objectif)object;

		long primaryKey = objectif.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Objectif> toCacheModel() {
		ObjectifCacheModel objectifCacheModel = new ObjectifCacheModel();

		objectifCacheModel.id = getId();

		objectifCacheModel.commercialId = getCommercialId();

		objectifCacheModel.type = getType();

		String type = objectifCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			objectifCacheModel.type = null;
		}

		objectifCacheModel.periode = getPeriode();

		String periode = objectifCacheModel.periode;

		if ((periode != null) && (periode.length() == 0)) {
			objectifCacheModel.periode = null;
		}

		objectifCacheModel.valeurCible = getValeurCible();

		objectifCacheModel.valeurReelle = getValeurReelle();

		objectifCacheModel.mois = getMois();

		objectifCacheModel.trimestre = getTrimestre();

		objectifCacheModel.annee = getAnnee();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			objectifCacheModel.createdAt = createdAt.getTime();
		}
		else {
			objectifCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			objectifCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			objectifCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return objectifCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Objectif, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Objectif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Objectif, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Objectif)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Objectif>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Objectif.class, ModelWrapper.class);

	}

	private long _id;
	private long _commercialId;
	private String _type;
	private String _periode;
	private int _valeurCible;
	private int _valeurReelle;
	private int _mois;
	private int _trimestre;
	private int _annee;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Objectif, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Objectif)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("commercial_id", _commercialId);
		_columnOriginalValues.put("type", _type);
		_columnOriginalValues.put("periode", _periode);
		_columnOriginalValues.put("valeur_cible", _valeurCible);
		_columnOriginalValues.put("valeur_reelle", _valeurReelle);
		_columnOriginalValues.put("mois", _mois);
		_columnOriginalValues.put("trimestre", _trimestre);
		_columnOriginalValues.put("annee", _annee);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("commercial_id", "commercialId");
		attributeNames.put("valeur_cible", "valeurCible");
		attributeNames.put("valeur_reelle", "valeurReelle");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("commercial_id", 2L);

		columnBitmasks.put("type", 4L);

		columnBitmasks.put("periode", 8L);

		columnBitmasks.put("valeur_cible", 16L);

		columnBitmasks.put("valeur_reelle", 32L);

		columnBitmasks.put("mois", 64L);

		columnBitmasks.put("trimestre", 128L);

		columnBitmasks.put("annee", 256L);

		columnBitmasks.put("created_at", 512L);

		columnBitmasks.put("updated_at", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Objectif _escapedModel;

}