/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Operation;
import com.df.lonis.ventesservice.model.OperationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Operation service. Represents a row in the &quot;operations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OperationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OperationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OperationImpl
 * @generated
 */
public class OperationModelImpl
	extends BaseModelImpl<Operation> implements OperationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a operation model instance should use the <code>Operation</code> interface instead.
	 */
	public static final String TABLE_NAME = "operations";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"code", Types.VARCHAR},
		{"libelle", Types.VARCHAR}, {"reference", Types.VARCHAR},
		{"montant", Types.BIGINT}, {"montant_reel", Types.BIGINT},
		{"statut", Types.VARCHAR}, {"terminal_id", Types.BIGINT},
		{"guichet", Types.VARCHAR}, {"date_operation", Types.TIMESTAMP},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("libelle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("montant", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("montant_reel", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statut", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("terminal_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("guichet", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_operation", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table operations (id LONG not null primary key IDENTITY,code VARCHAR(75) null,libelle VARCHAR(75) null,reference VARCHAR(75) null,montant LONG,montant_reel LONG,statut VARCHAR(75) null,terminal_id LONG,guichet VARCHAR(75) null,date_operation DATE null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table operations";

	public static final String ORDER_BY_JPQL =
		" ORDER BY operation.dateOperation DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY operations.date_operation DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REFERENCE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUT_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERMINALID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATEOPERATION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OperationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Operation.class;
	}

	@Override
	public String getModelClassName() {
		return Operation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Operation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Operation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Operation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Operation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Operation, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Operation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Operation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Operation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Operation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Operation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Operation, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Operation, Object>>();

			attributeGetterFunctions.put("id", Operation::getId);
			attributeGetterFunctions.put("code", Operation::getCode);
			attributeGetterFunctions.put("libelle", Operation::getLibelle);
			attributeGetterFunctions.put("reference", Operation::getReference);
			attributeGetterFunctions.put("montant", Operation::getMontant);
			attributeGetterFunctions.put(
				"montantReel", Operation::getMontantReel);
			attributeGetterFunctions.put("statut", Operation::getStatut);
			attributeGetterFunctions.put(
				"terminalId", Operation::getTerminalId);
			attributeGetterFunctions.put("guichet", Operation::getGuichet);
			attributeGetterFunctions.put(
				"dateOperation", Operation::getDateOperation);
			attributeGetterFunctions.put("createdAt", Operation::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Operation::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Operation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Operation, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Operation, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Operation, Long>)Operation::setId);
			attributeSetterBiConsumers.put(
				"code", (BiConsumer<Operation, String>)Operation::setCode);
			attributeSetterBiConsumers.put(
				"libelle",
				(BiConsumer<Operation, String>)Operation::setLibelle);
			attributeSetterBiConsumers.put(
				"reference",
				(BiConsumer<Operation, String>)Operation::setReference);
			attributeSetterBiConsumers.put(
				"montant", (BiConsumer<Operation, Long>)Operation::setMontant);
			attributeSetterBiConsumers.put(
				"montantReel",
				(BiConsumer<Operation, Long>)Operation::setMontantReel);
			attributeSetterBiConsumers.put(
				"statut", (BiConsumer<Operation, String>)Operation::setStatut);
			attributeSetterBiConsumers.put(
				"terminalId",
				(BiConsumer<Operation, Long>)Operation::setTerminalId);
			attributeSetterBiConsumers.put(
				"guichet",
				(BiConsumer<Operation, String>)Operation::setGuichet);
			attributeSetterBiConsumers.put(
				"dateOperation",
				(BiConsumer<Operation, Date>)Operation::setDateOperation);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Operation, Date>)Operation::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Operation, Date>)Operation::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	@Override
	public String getLibelle() {
		if (_libelle == null) {
			return "";
		}
		else {
			return _libelle;
		}
	}

	@Override
	public void setLibelle(String libelle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_libelle = libelle;
	}

	@Override
	public String getReference() {
		if (_reference == null) {
			return "";
		}
		else {
			return _reference;
		}
	}

	@Override
	public void setReference(String reference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reference = reference;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalReference() {
		return getColumnOriginalValue("reference");
	}

	@Override
	public long getMontant() {
		return _montant;
	}

	@Override
	public void setMontant(long montant) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_montant = montant;
	}

	@Override
	public long getMontantReel() {
		return _montantReel;
	}

	@Override
	public void setMontantReel(long montantReel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_montantReel = montantReel;
	}

	@Override
	public String getStatut() {
		if (_statut == null) {
			return "";
		}
		else {
			return _statut;
		}
	}

	@Override
	public void setStatut(String statut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statut = statut;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatut() {
		return getColumnOriginalValue("statut");
	}

	@Override
	public long getTerminalId() {
		return _terminalId;
	}

	@Override
	public void setTerminalId(long terminalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_terminalId = terminalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTerminalId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("terminal_id"));
	}

	@Override
	public String getGuichet() {
		if (_guichet == null) {
			return "";
		}
		else {
			return _guichet;
		}
	}

	@Override
	public void setGuichet(String guichet) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_guichet = guichet;
	}

	@Override
	public Date getDateOperation() {
		return _dateOperation;
	}

	@Override
	public void setDateOperation(Date dateOperation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOperation = dateOperation;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Operation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Operation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Operation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OperationImpl operationImpl = new OperationImpl();

		operationImpl.setId(getId());
		operationImpl.setCode(getCode());
		operationImpl.setLibelle(getLibelle());
		operationImpl.setReference(getReference());
		operationImpl.setMontant(getMontant());
		operationImpl.setMontantReel(getMontantReel());
		operationImpl.setStatut(getStatut());
		operationImpl.setTerminalId(getTerminalId());
		operationImpl.setGuichet(getGuichet());
		operationImpl.setDateOperation(getDateOperation());
		operationImpl.setCreatedAt(getCreatedAt());
		operationImpl.setUpdatedAt(getUpdatedAt());

		operationImpl.resetOriginalValues();

		return operationImpl;
	}

	@Override
	public Operation cloneWithOriginalValues() {
		OperationImpl operationImpl = new OperationImpl();

		operationImpl.setId(this.<Long>getColumnOriginalValue("id"));
		operationImpl.setCode(this.<String>getColumnOriginalValue("code"));
		operationImpl.setLibelle(
			this.<String>getColumnOriginalValue("libelle"));
		operationImpl.setReference(
			this.<String>getColumnOriginalValue("reference"));
		operationImpl.setMontant(this.<Long>getColumnOriginalValue("montant"));
		operationImpl.setMontantReel(
			this.<Long>getColumnOriginalValue("montant_reel"));
		operationImpl.setStatut(this.<String>getColumnOriginalValue("statut"));
		operationImpl.setTerminalId(
			this.<Long>getColumnOriginalValue("terminal_id"));
		operationImpl.setGuichet(
			this.<String>getColumnOriginalValue("guichet"));
		operationImpl.setDateOperation(
			this.<Date>getColumnOriginalValue("date_operation"));
		operationImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		operationImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return operationImpl;
	}

	@Override
	public int compareTo(Operation operation) {
		int value = 0;

		value = DateUtil.compareTo(
			getDateOperation(), operation.getDateOperation());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Operation)) {
			return false;
		}

		Operation operation = (Operation)object;

		long primaryKey = operation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Operation> toCacheModel() {
		OperationCacheModel operationCacheModel = new OperationCacheModel();

		operationCacheModel.id = getId();

		operationCacheModel.code = getCode();

		String code = operationCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			operationCacheModel.code = null;
		}

		operationCacheModel.libelle = getLibelle();

		String libelle = operationCacheModel.libelle;

		if ((libelle != null) && (libelle.length() == 0)) {
			operationCacheModel.libelle = null;
		}

		operationCacheModel.reference = getReference();

		String reference = operationCacheModel.reference;

		if ((reference != null) && (reference.length() == 0)) {
			operationCacheModel.reference = null;
		}

		operationCacheModel.montant = getMontant();

		operationCacheModel.montantReel = getMontantReel();

		operationCacheModel.statut = getStatut();

		String statut = operationCacheModel.statut;

		if ((statut != null) && (statut.length() == 0)) {
			operationCacheModel.statut = null;
		}

		operationCacheModel.terminalId = getTerminalId();

		operationCacheModel.guichet = getGuichet();

		String guichet = operationCacheModel.guichet;

		if ((guichet != null) && (guichet.length() == 0)) {
			operationCacheModel.guichet = null;
		}

		Date dateOperation = getDateOperation();

		if (dateOperation != null) {
			operationCacheModel.dateOperation = dateOperation.getTime();
		}
		else {
			operationCacheModel.dateOperation = Long.MIN_VALUE;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			operationCacheModel.createdAt = createdAt.getTime();
		}
		else {
			operationCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			operationCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			operationCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return operationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Operation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Operation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Operation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Operation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Operation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Operation.class, ModelWrapper.class);

	}

	private long _id;
	private String _code;
	private String _libelle;
	private String _reference;
	private long _montant;
	private long _montantReel;
	private String _statut;
	private long _terminalId;
	private String _guichet;
	private Date _dateOperation;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Operation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Operation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("libelle", _libelle);
		_columnOriginalValues.put("reference", _reference);
		_columnOriginalValues.put("montant", _montant);
		_columnOriginalValues.put("montant_reel", _montantReel);
		_columnOriginalValues.put("statut", _statut);
		_columnOriginalValues.put("terminal_id", _terminalId);
		_columnOriginalValues.put("guichet", _guichet);
		_columnOriginalValues.put("date_operation", _dateOperation);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("montant_reel", "montantReel");
		attributeNames.put("terminal_id", "terminalId");
		attributeNames.put("date_operation", "dateOperation");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("code", 2L);

		columnBitmasks.put("libelle", 4L);

		columnBitmasks.put("reference", 8L);

		columnBitmasks.put("montant", 16L);

		columnBitmasks.put("montant_reel", 32L);

		columnBitmasks.put("statut", 64L);

		columnBitmasks.put("terminal_id", 128L);

		columnBitmasks.put("guichet", 256L);

		columnBitmasks.put("date_operation", 512L);

		columnBitmasks.put("created_at", 1024L);

		columnBitmasks.put("updated_at", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Operation _escapedModel;

}