/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Operation;
import com.df.lonis.ventesservice.service.OperationLocalServiceUtil;

/**
 * The extended model base implementation for the Operation service. Represents a row in the &quot;operations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OperationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OperationImpl
 * @see Operation
 * @generated
 */
public abstract class OperationBaseImpl
	extends OperationModelImpl implements Operation {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a operation model instance should use the <code>Operation</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			OperationLocalServiceUtil.addOperation(this);
		}
		else {
			OperationLocalServiceUtil.updateOperation(this);
		}
	}

}