/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Produit;
import com.df.lonis.ventesservice.service.ProduitLocalServiceUtil;

/**
 * The extended model base implementation for the Produit service. Represents a row in the &quot;produits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProduitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProduitImpl
 * @see Produit
 * @generated
 */
public abstract class ProduitBaseImpl
	extends ProduitModelImpl implements Produit {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a produit model instance should use the <code>Produit</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProduitLocalServiceUtil.addProduit(this);
		}
		else {
			ProduitLocalServiceUtil.updateProduit(this);
		}
	}

}