/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Produit;
import com.df.lonis.ventesservice.model.ProduitModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Produit service. Represents a row in the &quot;produits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProduitModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProduitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProduitImpl
 * @generated
 */
public class ProduitModelImpl
	extends BaseModelImpl<Produit> implements ProduitModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a produit model instance should use the <code>Produit</code> interface instead.
	 */
	public static final String TABLE_NAME = "produits";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"code", Types.VARCHAR},
		{"libelle", Types.VARCHAR}, {"abreviation", Types.VARCHAR},
		{"active", Types.BOOLEAN}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("libelle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("abreviation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table produits (id LONG not null primary key IDENTITY,code VARCHAR(75) null,libelle VARCHAR(75) null,abreviation VARCHAR(75) null,active BOOLEAN,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table produits";

	public static final String ORDER_BY_JPQL = " ORDER BY produit.libelle ASC";

	public static final String ORDER_BY_SQL = " ORDER BY produits.libelle ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LIBELLE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProduitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Produit.class;
	}

	@Override
	public String getModelClassName() {
		return Produit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Produit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Produit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Produit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Produit)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Produit, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Produit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Produit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Produit, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Produit, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Produit, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Produit, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Produit, Object>>();

			attributeGetterFunctions.put("id", Produit::getId);
			attributeGetterFunctions.put("code", Produit::getCode);
			attributeGetterFunctions.put("libelle", Produit::getLibelle);
			attributeGetterFunctions.put(
				"abreviation", Produit::getAbreviation);
			attributeGetterFunctions.put("active", Produit::getActive);
			attributeGetterFunctions.put("createdAt", Produit::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Produit::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Produit, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Produit, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Produit, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Produit, Long>)Produit::setId);
			attributeSetterBiConsumers.put(
				"code", (BiConsumer<Produit, String>)Produit::setCode);
			attributeSetterBiConsumers.put(
				"libelle", (BiConsumer<Produit, String>)Produit::setLibelle);
			attributeSetterBiConsumers.put(
				"abreviation",
				(BiConsumer<Produit, String>)Produit::setAbreviation);
			attributeSetterBiConsumers.put(
				"active", (BiConsumer<Produit, Boolean>)Produit::setActive);
			attributeSetterBiConsumers.put(
				"createdAt", (BiConsumer<Produit, Date>)Produit::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt", (BiConsumer<Produit, Date>)Produit::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code");
	}

	@Override
	public String getLibelle() {
		if (_libelle == null) {
			return "";
		}
		else {
			return _libelle;
		}
	}

	@Override
	public void setLibelle(String libelle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_libelle = libelle;
	}

	@Override
	public String getAbreviation() {
		if (_abreviation == null) {
			return "";
		}
		else {
			return _abreviation;
		}
	}

	@Override
	public void setAbreviation(String abreviation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_abreviation = abreviation;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Produit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Produit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Produit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProduitImpl produitImpl = new ProduitImpl();

		produitImpl.setId(getId());
		produitImpl.setCode(getCode());
		produitImpl.setLibelle(getLibelle());
		produitImpl.setAbreviation(getAbreviation());
		produitImpl.setActive(isActive());
		produitImpl.setCreatedAt(getCreatedAt());
		produitImpl.setUpdatedAt(getUpdatedAt());

		produitImpl.resetOriginalValues();

		return produitImpl;
	}

	@Override
	public Produit cloneWithOriginalValues() {
		ProduitImpl produitImpl = new ProduitImpl();

		produitImpl.setId(this.<Long>getColumnOriginalValue("id"));
		produitImpl.setCode(this.<String>getColumnOriginalValue("code"));
		produitImpl.setLibelle(this.<String>getColumnOriginalValue("libelle"));
		produitImpl.setAbreviation(
			this.<String>getColumnOriginalValue("abreviation"));
		produitImpl.setActive(this.<Boolean>getColumnOriginalValue("active"));
		produitImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		produitImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return produitImpl;
	}

	@Override
	public int compareTo(Produit produit) {
		int value = 0;

		value = getLibelle().compareTo(produit.getLibelle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Produit)) {
			return false;
		}

		Produit produit = (Produit)object;

		long primaryKey = produit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Produit> toCacheModel() {
		ProduitCacheModel produitCacheModel = new ProduitCacheModel();

		produitCacheModel.id = getId();

		produitCacheModel.code = getCode();

		String code = produitCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			produitCacheModel.code = null;
		}

		produitCacheModel.libelle = getLibelle();

		String libelle = produitCacheModel.libelle;

		if ((libelle != null) && (libelle.length() == 0)) {
			produitCacheModel.libelle = null;
		}

		produitCacheModel.abreviation = getAbreviation();

		String abreviation = produitCacheModel.abreviation;

		if ((abreviation != null) && (abreviation.length() == 0)) {
			produitCacheModel.abreviation = null;
		}

		produitCacheModel.active = isActive();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			produitCacheModel.createdAt = createdAt.getTime();
		}
		else {
			produitCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			produitCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			produitCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return produitCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Produit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Produit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Produit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Produit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Produit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Produit.class, ModelWrapper.class);

	}

	private long _id;
	private String _code;
	private String _libelle;
	private String _abreviation;
	private boolean _active;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Produit, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Produit)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("libelle", _libelle);
		_columnOriginalValues.put("abreviation", _abreviation);
		_columnOriginalValues.put("active", _active);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("code", 2L);

		columnBitmasks.put("libelle", 4L);

		columnBitmasks.put("abreviation", 8L);

		columnBitmasks.put("active", 16L);

		columnBitmasks.put("created_at", 32L);

		columnBitmasks.put("updated_at", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Produit _escapedModel;

}