/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Site;
import com.df.lonis.ventesservice.model.SiteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Site service. Represents a row in the &quot;sites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SiteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SiteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteImpl
 * @generated
 */
public class SiteModelImpl extends BaseModelImpl<Site> implements SiteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a site model instance should use the <code>Site</code> interface instead.
	 */
	public static final String TABLE_NAME = "sites";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"libelle", Types.VARCHAR},
		{"type", Types.INTEGER}, {"parent_id", Types.BIGINT},
		{"code", Types.VARCHAR}, {"code_provinov", Types.VARCHAR},
		{"status", Types.BOOLEAN}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("libelle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("parent_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_provinov", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sites (id LONG not null primary key IDENTITY,libelle VARCHAR(75) null,type INTEGER,parent_id LONG,code VARCHAR(75) null,code_provinov VARCHAR(75) null,status BOOLEAN,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table sites";

	public static final String ORDER_BY_JPQL = " ORDER BY site.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY sites.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SiteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Site.class;
	}

	@Override
	public String getModelClassName() {
		return Site.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Site, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Site, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Site, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Site)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Site, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Site, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Site)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Site, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Site, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Site, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Site, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Site, Object>>();

			attributeGetterFunctions.put("id", Site::getId);
			attributeGetterFunctions.put("libelle", Site::getLibelle);
			attributeGetterFunctions.put("type", Site::getType);
			attributeGetterFunctions.put("parentId", Site::getParentId);
			attributeGetterFunctions.put("code", Site::getCode);
			attributeGetterFunctions.put("codeProvinov", Site::getCodeProvinov);
			attributeGetterFunctions.put("status", Site::getStatus);
			attributeGetterFunctions.put("createdAt", Site::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Site::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Site, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Site, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Site, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Site, Long>)Site::setId);
			attributeSetterBiConsumers.put(
				"libelle", (BiConsumer<Site, String>)Site::setLibelle);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<Site, Integer>)Site::setType);
			attributeSetterBiConsumers.put(
				"parentId", (BiConsumer<Site, Long>)Site::setParentId);
			attributeSetterBiConsumers.put(
				"code", (BiConsumer<Site, String>)Site::setCode);
			attributeSetterBiConsumers.put(
				"codeProvinov",
				(BiConsumer<Site, String>)Site::setCodeProvinov);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Site, Boolean>)Site::setStatus);
			attributeSetterBiConsumers.put(
				"createdAt", (BiConsumer<Site, Date>)Site::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt", (BiConsumer<Site, Date>)Site::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getLibelle() {
		if (_libelle == null) {
			return "";
		}
		else {
			return _libelle;
		}
	}

	@Override
	public void setLibelle(String libelle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_libelle = libelle;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	@Override
	public String getCodeProvinov() {
		if (_codeProvinov == null) {
			return "";
		}
		else {
			return _codeProvinov;
		}
	}

	@Override
	public void setCodeProvinov(String codeProvinov) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codeProvinov = codeProvinov;
	}

	@Override
	public boolean getStatus() {
		return _status;
	}

	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Site.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Site toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Site>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SiteImpl siteImpl = new SiteImpl();

		siteImpl.setId(getId());
		siteImpl.setLibelle(getLibelle());
		siteImpl.setType(getType());
		siteImpl.setParentId(getParentId());
		siteImpl.setCode(getCode());
		siteImpl.setCodeProvinov(getCodeProvinov());
		siteImpl.setStatus(isStatus());
		siteImpl.setCreatedAt(getCreatedAt());
		siteImpl.setUpdatedAt(getUpdatedAt());

		siteImpl.resetOriginalValues();

		return siteImpl;
	}

	@Override
	public Site cloneWithOriginalValues() {
		SiteImpl siteImpl = new SiteImpl();

		siteImpl.setId(this.<Long>getColumnOriginalValue("id"));
		siteImpl.setLibelle(this.<String>getColumnOriginalValue("libelle"));
		siteImpl.setType(this.<Integer>getColumnOriginalValue("type"));
		siteImpl.setParentId(this.<Long>getColumnOriginalValue("parent_id"));
		siteImpl.setCode(this.<String>getColumnOriginalValue("code"));
		siteImpl.setCodeProvinov(
			this.<String>getColumnOriginalValue("code_provinov"));
		siteImpl.setStatus(this.<Boolean>getColumnOriginalValue("status"));
		siteImpl.setCreatedAt(this.<Date>getColumnOriginalValue("created_at"));
		siteImpl.setUpdatedAt(this.<Date>getColumnOriginalValue("updated_at"));

		return siteImpl;
	}

	@Override
	public int compareTo(Site site) {
		long primaryKey = site.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Site)) {
			return false;
		}

		Site site = (Site)object;

		long primaryKey = site.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Site> toCacheModel() {
		SiteCacheModel siteCacheModel = new SiteCacheModel();

		siteCacheModel.id = getId();

		siteCacheModel.libelle = getLibelle();

		String libelle = siteCacheModel.libelle;

		if ((libelle != null) && (libelle.length() == 0)) {
			siteCacheModel.libelle = null;
		}

		siteCacheModel.type = getType();

		siteCacheModel.parentId = getParentId();

		siteCacheModel.code = getCode();

		String code = siteCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			siteCacheModel.code = null;
		}

		siteCacheModel.codeProvinov = getCodeProvinov();

		String codeProvinov = siteCacheModel.codeProvinov;

		if ((codeProvinov != null) && (codeProvinov.length() == 0)) {
			siteCacheModel.codeProvinov = null;
		}

		siteCacheModel.status = isStatus();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			siteCacheModel.createdAt = createdAt.getTime();
		}
		else {
			siteCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			siteCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			siteCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return siteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Site, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Site, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Site, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Site)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Site>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Site.class, ModelWrapper.class);

	}

	private long _id;
	private String _libelle;
	private int _type;
	private long _parentId;
	private String _code;
	private String _codeProvinov;
	private boolean _status;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Site, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Site)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("libelle", _libelle);
		_columnOriginalValues.put("type", _type);
		_columnOriginalValues.put("parent_id", _parentId);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("code_provinov", _codeProvinov);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("parent_id", "parentId");
		attributeNames.put("code_provinov", "codeProvinov");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("libelle", 2L);

		columnBitmasks.put("type", 4L);

		columnBitmasks.put("parent_id", 8L);

		columnBitmasks.put("code", 16L);

		columnBitmasks.put("code_provinov", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("created_at", 128L);

		columnBitmasks.put("updated_at", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Site _escapedModel;

}