/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.SiteCommercial;
import com.df.lonis.ventesservice.model.SiteCommercialModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SiteCommercial service. Represents a row in the &quot;site_commerciaux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SiteCommercialModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SiteCommercialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteCommercialImpl
 * @generated
 */
public class SiteCommercialModelImpl
	extends BaseModelImpl<SiteCommercial> implements SiteCommercialModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a site commercial model instance should use the <code>SiteCommercial</code> interface instead.
	 */
	public static final String TABLE_NAME = "site_commerciaux";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"site_id", Types.BIGINT},
		{"commercial_id", Types.BIGINT}, {"date_debut", Types.TIMESTAMP},
		{"date_fin", Types.TIMESTAMP}, {"is_principal", Types.BOOLEAN},
		{"created_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("site_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercial_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("date_debut", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("date_fin", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("is_principal", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table site_commerciaux (id LONG not null primary key IDENTITY,site_id LONG,commercial_id LONG,date_debut DATE null,date_fin DATE null,is_principal BOOLEAN,created_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table site_commerciaux";

	public static final String ORDER_BY_JPQL =
		" ORDER BY siteCommercial.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY site_commerciaux.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCIALID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SITEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SiteCommercialModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SiteCommercial.class;
	}

	@Override
	public String getModelClassName() {
		return SiteCommercial.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SiteCommercial, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SiteCommercial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SiteCommercial, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SiteCommercial)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SiteCommercial, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SiteCommercial, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SiteCommercial)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SiteCommercial, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SiteCommercial, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SiteCommercial, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SiteCommercial, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<SiteCommercial, Object>>();

			attributeGetterFunctions.put("id", SiteCommercial::getId);
			attributeGetterFunctions.put("siteId", SiteCommercial::getSiteId);
			attributeGetterFunctions.put(
				"commercialId", SiteCommercial::getCommercialId);
			attributeGetterFunctions.put(
				"dateDebut", SiteCommercial::getDateDebut);
			attributeGetterFunctions.put("dateFin", SiteCommercial::getDateFin);
			attributeGetterFunctions.put(
				"isPrincipal", SiteCommercial::getIsPrincipal);
			attributeGetterFunctions.put(
				"createdAt", SiteCommercial::getCreatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SiteCommercial, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SiteCommercial, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<SiteCommercial, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<SiteCommercial, Long>)SiteCommercial::setId);
			attributeSetterBiConsumers.put(
				"siteId",
				(BiConsumer<SiteCommercial, Long>)SiteCommercial::setSiteId);
			attributeSetterBiConsumers.put(
				"commercialId",
				(BiConsumer<SiteCommercial, Long>)
					SiteCommercial::setCommercialId);
			attributeSetterBiConsumers.put(
				"dateDebut",
				(BiConsumer<SiteCommercial, Date>)SiteCommercial::setDateDebut);
			attributeSetterBiConsumers.put(
				"dateFin",
				(BiConsumer<SiteCommercial, Date>)SiteCommercial::setDateFin);
			attributeSetterBiConsumers.put(
				"isPrincipal",
				(BiConsumer<SiteCommercial, Boolean>)
					SiteCommercial::setIsPrincipal);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<SiteCommercial, Date>)SiteCommercial::setCreatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getSiteId() {
		return _siteId;
	}

	@Override
	public void setSiteId(long siteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_siteId = siteId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSiteId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("site_id"));
	}

	@Override
	public long getCommercialId() {
		return _commercialId;
	}

	@Override
	public void setCommercialId(long commercialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialId = commercialId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommercialId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commercial_id"));
	}

	@Override
	public Date getDateDebut() {
		return _dateDebut;
	}

	@Override
	public void setDateDebut(Date dateDebut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateDebut = dateDebut;
	}

	@Override
	public Date getDateFin() {
		return _dateFin;
	}

	@Override
	public void setDateFin(Date dateFin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateFin = dateFin;
	}

	@Override
	public boolean getIsPrincipal() {
		return _isPrincipal;
	}

	@Override
	public boolean isIsPrincipal() {
		return _isPrincipal;
	}

	@Override
	public void setIsPrincipal(boolean isPrincipal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isPrincipal = isPrincipal;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SiteCommercial.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SiteCommercial toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SiteCommercial>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SiteCommercialImpl siteCommercialImpl = new SiteCommercialImpl();

		siteCommercialImpl.setId(getId());
		siteCommercialImpl.setSiteId(getSiteId());
		siteCommercialImpl.setCommercialId(getCommercialId());
		siteCommercialImpl.setDateDebut(getDateDebut());
		siteCommercialImpl.setDateFin(getDateFin());
		siteCommercialImpl.setIsPrincipal(isIsPrincipal());
		siteCommercialImpl.setCreatedAt(getCreatedAt());

		siteCommercialImpl.resetOriginalValues();

		return siteCommercialImpl;
	}

	@Override
	public SiteCommercial cloneWithOriginalValues() {
		SiteCommercialImpl siteCommercialImpl = new SiteCommercialImpl();

		siteCommercialImpl.setId(this.<Long>getColumnOriginalValue("id"));
		siteCommercialImpl.setSiteId(
			this.<Long>getColumnOriginalValue("site_id"));
		siteCommercialImpl.setCommercialId(
			this.<Long>getColumnOriginalValue("commercial_id"));
		siteCommercialImpl.setDateDebut(
			this.<Date>getColumnOriginalValue("date_debut"));
		siteCommercialImpl.setDateFin(
			this.<Date>getColumnOriginalValue("date_fin"));
		siteCommercialImpl.setIsPrincipal(
			this.<Boolean>getColumnOriginalValue("is_principal"));
		siteCommercialImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));

		return siteCommercialImpl;
	}

	@Override
	public int compareTo(SiteCommercial siteCommercial) {
		long primaryKey = siteCommercial.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SiteCommercial)) {
			return false;
		}

		SiteCommercial siteCommercial = (SiteCommercial)object;

		long primaryKey = siteCommercial.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SiteCommercial> toCacheModel() {
		SiteCommercialCacheModel siteCommercialCacheModel =
			new SiteCommercialCacheModel();

		siteCommercialCacheModel.id = getId();

		siteCommercialCacheModel.siteId = getSiteId();

		siteCommercialCacheModel.commercialId = getCommercialId();

		Date dateDebut = getDateDebut();

		if (dateDebut != null) {
			siteCommercialCacheModel.dateDebut = dateDebut.getTime();
		}
		else {
			siteCommercialCacheModel.dateDebut = Long.MIN_VALUE;
		}

		Date dateFin = getDateFin();

		if (dateFin != null) {
			siteCommercialCacheModel.dateFin = dateFin.getTime();
		}
		else {
			siteCommercialCacheModel.dateFin = Long.MIN_VALUE;
		}

		siteCommercialCacheModel.isPrincipal = isIsPrincipal();

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			siteCommercialCacheModel.createdAt = createdAt.getTime();
		}
		else {
			siteCommercialCacheModel.createdAt = Long.MIN_VALUE;
		}

		return siteCommercialCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SiteCommercial, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SiteCommercial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SiteCommercial, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SiteCommercial)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SiteCommercial>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SiteCommercial.class, ModelWrapper.class);

	}

	private long _id;
	private long _siteId;
	private long _commercialId;
	private Date _dateDebut;
	private Date _dateFin;
	private boolean _isPrincipal;
	private Date _createdAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SiteCommercial, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SiteCommercial)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("site_id", _siteId);
		_columnOriginalValues.put("commercial_id", _commercialId);
		_columnOriginalValues.put("date_debut", _dateDebut);
		_columnOriginalValues.put("date_fin", _dateFin);
		_columnOriginalValues.put("is_principal", _isPrincipal);
		_columnOriginalValues.put("created_at", _createdAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("site_id", "siteId");
		attributeNames.put("commercial_id", "commercialId");
		attributeNames.put("date_debut", "dateDebut");
		attributeNames.put("date_fin", "dateFin");
		attributeNames.put("is_principal", "isPrincipal");
		attributeNames.put("created_at", "createdAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("site_id", 2L);

		columnBitmasks.put("commercial_id", 4L);

		columnBitmasks.put("date_debut", 8L);

		columnBitmasks.put("date_fin", 16L);

		columnBitmasks.put("is_principal", 32L);

		columnBitmasks.put("created_at", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SiteCommercial _escapedModel;

}