/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Terminal;
import com.df.lonis.ventesservice.model.TerminalModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Terminal service. Represents a row in the &quot;terminals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TerminalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TerminalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TerminalImpl
 * @generated
 */
public class TerminalModelImpl
	extends BaseModelImpl<Terminal> implements TerminalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a terminal model instance should use the <code>Terminal</code> interface instead.
	 */
	public static final String TABLE_NAME = "terminals";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"code_terminal", Types.VARCHAR},
		{"concessionnaire_id", Types.BIGINT},
		{"concessionnaire_code", Types.VARCHAR}, {"produit_id", Types.BIGINT},
		{"concessionnaire_produit_code", Types.VARCHAR},
		{"site_id", Types.BIGINT}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}, {"adresse", Types.VARCHAR},
		{"statut_validation", Types.VARCHAR}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code_terminal", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("concessionnaire_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("concessionnaire_code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("produit_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("concessionnaire_produit_code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("site_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("adresse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statut_validation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table terminals (id LONG not null primary key IDENTITY,code_terminal VARCHAR(75) null,concessionnaire_id LONG,concessionnaire_code VARCHAR(75) null,produit_id LONG,concessionnaire_produit_code VARCHAR(75) null,site_id LONG,latitude DOUBLE,longitude DOUBLE,adresse VARCHAR(75) null,statut_validation VARCHAR(75) null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table terminals";

	public static final String ORDER_BY_JPQL = " ORDER BY terminal.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY terminals.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONCESSIONNAIREID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONCESSIONNAIREPRODUITCODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SITEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUTVALIDATION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TerminalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Terminal.class;
	}

	@Override
	public String getModelClassName() {
		return Terminal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Terminal, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Terminal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Terminal, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Terminal)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Terminal, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Terminal, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Terminal)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Terminal, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Terminal, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Terminal, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Terminal, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Terminal, Object>>();

			attributeGetterFunctions.put("id", Terminal::getId);
			attributeGetterFunctions.put(
				"codeTerminal", Terminal::getCodeTerminal);
			attributeGetterFunctions.put(
				"concessionnaireId", Terminal::getConcessionnaireId);
			attributeGetterFunctions.put(
				"concessionnaireCode", Terminal::getConcessionnaireCode);
			attributeGetterFunctions.put("produitId", Terminal::getProduitId);
			attributeGetterFunctions.put(
				"concessionnaireProduitCode",
				Terminal::getConcessionnaireProduitCode);
			attributeGetterFunctions.put("siteId", Terminal::getSiteId);
			attributeGetterFunctions.put("latitude", Terminal::getLatitude);
			attributeGetterFunctions.put("longitude", Terminal::getLongitude);
			attributeGetterFunctions.put("adresse", Terminal::getAdresse);
			attributeGetterFunctions.put(
				"statutValidation", Terminal::getStatutValidation);
			attributeGetterFunctions.put("createdAt", Terminal::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Terminal::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Terminal, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Terminal, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Terminal, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Terminal, Long>)Terminal::setId);
			attributeSetterBiConsumers.put(
				"codeTerminal",
				(BiConsumer<Terminal, String>)Terminal::setCodeTerminal);
			attributeSetterBiConsumers.put(
				"concessionnaireId",
				(BiConsumer<Terminal, Long>)Terminal::setConcessionnaireId);
			attributeSetterBiConsumers.put(
				"concessionnaireCode",
				(BiConsumer<Terminal, String>)Terminal::setConcessionnaireCode);
			attributeSetterBiConsumers.put(
				"produitId",
				(BiConsumer<Terminal, Long>)Terminal::setProduitId);
			attributeSetterBiConsumers.put(
				"concessionnaireProduitCode",
				(BiConsumer<Terminal, String>)
					Terminal::setConcessionnaireProduitCode);
			attributeSetterBiConsumers.put(
				"siteId", (BiConsumer<Terminal, Long>)Terminal::setSiteId);
			attributeSetterBiConsumers.put(
				"latitude",
				(BiConsumer<Terminal, Double>)Terminal::setLatitude);
			attributeSetterBiConsumers.put(
				"longitude",
				(BiConsumer<Terminal, Double>)Terminal::setLongitude);
			attributeSetterBiConsumers.put(
				"adresse", (BiConsumer<Terminal, String>)Terminal::setAdresse);
			attributeSetterBiConsumers.put(
				"statutValidation",
				(BiConsumer<Terminal, String>)Terminal::setStatutValidation);
			attributeSetterBiConsumers.put(
				"createdAt",
				(BiConsumer<Terminal, Date>)Terminal::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt",
				(BiConsumer<Terminal, Date>)Terminal::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getCodeTerminal() {
		if (_codeTerminal == null) {
			return "";
		}
		else {
			return _codeTerminal;
		}
	}

	@Override
	public void setCodeTerminal(String codeTerminal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codeTerminal = codeTerminal;
	}

	@Override
	public long getConcessionnaireId() {
		return _concessionnaireId;
	}

	@Override
	public void setConcessionnaireId(long concessionnaireId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessionnaireId = concessionnaireId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalConcessionnaireId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("concessionnaire_id"));
	}

	@Override
	public String getConcessionnaireCode() {
		if (_concessionnaireCode == null) {
			return "";
		}
		else {
			return _concessionnaireCode;
		}
	}

	@Override
	public void setConcessionnaireCode(String concessionnaireCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessionnaireCode = concessionnaireCode;
	}

	@Override
	public long getProduitId() {
		return _produitId;
	}

	@Override
	public void setProduitId(long produitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_produitId = produitId;
	}

	@Override
	public String getConcessionnaireProduitCode() {
		if (_concessionnaireProduitCode == null) {
			return "";
		}
		else {
			return _concessionnaireProduitCode;
		}
	}

	@Override
	public void setConcessionnaireProduitCode(
		String concessionnaireProduitCode) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessionnaireProduitCode = concessionnaireProduitCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalConcessionnaireProduitCode() {
		return getColumnOriginalValue("concessionnaire_produit_code");
	}

	@Override
	public long getSiteId() {
		return _siteId;
	}

	@Override
	public void setSiteId(long siteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_siteId = siteId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSiteId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("site_id"));
	}

	@Override
	public Double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(Double latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@Override
	public Double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(Double longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	@Override
	public String getAdresse() {
		if (_adresse == null) {
			return "";
		}
		else {
			return _adresse;
		}
	}

	@Override
	public void setAdresse(String adresse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_adresse = adresse;
	}

	@Override
	public String getStatutValidation() {
		if (_statutValidation == null) {
			return "";
		}
		else {
			return _statutValidation;
		}
	}

	@Override
	public void setStatutValidation(String statutValidation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statutValidation = statutValidation;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatutValidation() {
		return getColumnOriginalValue("statut_validation");
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Terminal.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Terminal toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Terminal>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TerminalImpl terminalImpl = new TerminalImpl();

		terminalImpl.setId(getId());
		terminalImpl.setCodeTerminal(getCodeTerminal());
		terminalImpl.setConcessionnaireId(getConcessionnaireId());
		terminalImpl.setConcessionnaireCode(getConcessionnaireCode());
		terminalImpl.setProduitId(getProduitId());
		terminalImpl.setConcessionnaireProduitCode(
			getConcessionnaireProduitCode());
		terminalImpl.setSiteId(getSiteId());
		terminalImpl.setLatitude(getLatitude());
		terminalImpl.setLongitude(getLongitude());
		terminalImpl.setAdresse(getAdresse());
		terminalImpl.setStatutValidation(getStatutValidation());
		terminalImpl.setCreatedAt(getCreatedAt());
		terminalImpl.setUpdatedAt(getUpdatedAt());

		terminalImpl.resetOriginalValues();

		return terminalImpl;
	}

	@Override
	public Terminal cloneWithOriginalValues() {
		TerminalImpl terminalImpl = new TerminalImpl();

		terminalImpl.setId(this.<Long>getColumnOriginalValue("id"));
		terminalImpl.setCodeTerminal(
			this.<String>getColumnOriginalValue("code_terminal"));
		terminalImpl.setConcessionnaireId(
			this.<Long>getColumnOriginalValue("concessionnaire_id"));
		terminalImpl.setConcessionnaireCode(
			this.<String>getColumnOriginalValue("concessionnaire_code"));
		terminalImpl.setProduitId(
			this.<Long>getColumnOriginalValue("produit_id"));
		terminalImpl.setConcessionnaireProduitCode(
			this.<String>getColumnOriginalValue(
				"concessionnaire_produit_code"));
		terminalImpl.setSiteId(this.<Long>getColumnOriginalValue("site_id"));
		terminalImpl.setLatitude(
			this.<Double>getColumnOriginalValue("latitude"));
		terminalImpl.setLongitude(
			this.<Double>getColumnOriginalValue("longitude"));
		terminalImpl.setAdresse(this.<String>getColumnOriginalValue("adresse"));
		terminalImpl.setStatutValidation(
			this.<String>getColumnOriginalValue("statut_validation"));
		terminalImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		terminalImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return terminalImpl;
	}

	@Override
	public int compareTo(Terminal terminal) {
		long primaryKey = terminal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Terminal)) {
			return false;
		}

		Terminal terminal = (Terminal)object;

		long primaryKey = terminal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Terminal> toCacheModel() {
		TerminalCacheModel terminalCacheModel = new TerminalCacheModel();

		terminalCacheModel.id = getId();

		terminalCacheModel.codeTerminal = getCodeTerminal();

		String codeTerminal = terminalCacheModel.codeTerminal;

		if ((codeTerminal != null) && (codeTerminal.length() == 0)) {
			terminalCacheModel.codeTerminal = null;
		}

		terminalCacheModel.concessionnaireId = getConcessionnaireId();

		terminalCacheModel.concessionnaireCode = getConcessionnaireCode();

		String concessionnaireCode = terminalCacheModel.concessionnaireCode;

		if ((concessionnaireCode != null) &&
			(concessionnaireCode.length() == 0)) {

			terminalCacheModel.concessionnaireCode = null;
		}

		terminalCacheModel.produitId = getProduitId();

		terminalCacheModel.concessionnaireProduitCode =
			getConcessionnaireProduitCode();

		String concessionnaireProduitCode =
			terminalCacheModel.concessionnaireProduitCode;

		if ((concessionnaireProduitCode != null) &&
			(concessionnaireProduitCode.length() == 0)) {

			terminalCacheModel.concessionnaireProduitCode = null;
		}

		terminalCacheModel.siteId = getSiteId();

		Double latitude = getLatitude();

		if (latitude != null) {
			terminalCacheModel.latitude = latitude;
		}

		Double longitude = getLongitude();

		if (longitude != null) {
			terminalCacheModel.longitude = longitude;
		}

		terminalCacheModel.adresse = getAdresse();

		String adresse = terminalCacheModel.adresse;

		if ((adresse != null) && (adresse.length() == 0)) {
			terminalCacheModel.adresse = null;
		}

		terminalCacheModel.statutValidation = getStatutValidation();

		String statutValidation = terminalCacheModel.statutValidation;

		if ((statutValidation != null) && (statutValidation.length() == 0)) {
			terminalCacheModel.statutValidation = null;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			terminalCacheModel.createdAt = createdAt.getTime();
		}
		else {
			terminalCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			terminalCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			terminalCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return terminalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Terminal, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Terminal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Terminal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Terminal)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Terminal>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Terminal.class, ModelWrapper.class);

	}

	private long _id;
	private String _codeTerminal;
	private long _concessionnaireId;
	private String _concessionnaireCode;
	private long _produitId;
	private String _concessionnaireProduitCode;
	private long _siteId;
	private Double _latitude;
	private Double _longitude;
	private String _adresse;
	private String _statutValidation;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Terminal, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Terminal)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("code_terminal", _codeTerminal);
		_columnOriginalValues.put("concessionnaire_id", _concessionnaireId);
		_columnOriginalValues.put("concessionnaire_code", _concessionnaireCode);
		_columnOriginalValues.put("produit_id", _produitId);
		_columnOriginalValues.put(
			"concessionnaire_produit_code", _concessionnaireProduitCode);
		_columnOriginalValues.put("site_id", _siteId);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
		_columnOriginalValues.put("adresse", _adresse);
		_columnOriginalValues.put("statut_validation", _statutValidation);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("code_terminal", "codeTerminal");
		attributeNames.put("concessionnaire_id", "concessionnaireId");
		attributeNames.put("concessionnaire_code", "concessionnaireCode");
		attributeNames.put("produit_id", "produitId");
		attributeNames.put(
			"concessionnaire_produit_code", "concessionnaireProduitCode");
		attributeNames.put("site_id", "siteId");
		attributeNames.put("statut_validation", "statutValidation");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("code_terminal", 2L);

		columnBitmasks.put("concessionnaire_id", 4L);

		columnBitmasks.put("concessionnaire_code", 8L);

		columnBitmasks.put("produit_id", 16L);

		columnBitmasks.put("concessionnaire_produit_code", 32L);

		columnBitmasks.put("site_id", 64L);

		columnBitmasks.put("latitude", 128L);

		columnBitmasks.put("longitude", 256L);

		columnBitmasks.put("adresse", 512L);

		columnBitmasks.put("statut_validation", 1024L);

		columnBitmasks.put("created_at", 2048L);

		columnBitmasks.put("updated_at", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Terminal _escapedModel;

}