/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Terminal;
import com.df.lonis.ventesservice.service.TerminalLocalServiceUtil;

/**
 * The extended model base implementation for the Terminal service. Represents a row in the &quot;terminals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TerminalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TerminalImpl
 * @see Terminal
 * @generated
 */
public abstract class TerminalBaseImpl
	extends TerminalModelImpl implements Terminal {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a terminal model instance should use the <code>Terminal</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TerminalLocalServiceUtil.addTerminal(this);
		}
		else {
			TerminalLocalServiceUtil.updateTerminal(this);
		}
	}

}