/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Visite;
import com.df.lonis.ventesservice.model.VisiteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Visite service. Represents a row in the &quot;visites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VisiteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VisiteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisiteImpl
 * @generated
 */
public class VisiteModelImpl
	extends BaseModelImpl<Visite> implements VisiteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a visite model instance should use the <code>Visite</code> interface instead.
	 */
	public static final String TABLE_NAME = "visites";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"commercial_id", Types.BIGINT},
		{"terminal_id", Types.BIGINT}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}, {"statut", Types.VARCHAR},
		{"type_controle", Types.VARCHAR}, {"date_visite", Types.TIMESTAMP},
		{"compte_rendu", Types.VARCHAR}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercial_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("terminal_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("statut", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_controle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_visite", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("compte_rendu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table visites (id LONG not null primary key IDENTITY,commercial_id LONG,terminal_id LONG,latitude DOUBLE,longitude DOUBLE,statut VARCHAR(75) null,type_controle VARCHAR(75) null,date_visite DATE null,compte_rendu VARCHAR(75) null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table visites";

	public static final String ORDER_BY_JPQL =
		" ORDER BY visite.dateVisite DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY visites.date_visite DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCIALID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATEVISITE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUT_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERMINALID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public VisiteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Visite.class;
	}

	@Override
	public String getModelClassName() {
		return Visite.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Visite, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Visite, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Visite, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Visite)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Visite, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Visite, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Visite)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Visite, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Visite, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Visite, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Visite, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Visite, Object>>();

			attributeGetterFunctions.put("id", Visite::getId);
			attributeGetterFunctions.put(
				"commercialId", Visite::getCommercialId);
			attributeGetterFunctions.put("terminalId", Visite::getTerminalId);
			attributeGetterFunctions.put("latitude", Visite::getLatitude);
			attributeGetterFunctions.put("longitude", Visite::getLongitude);
			attributeGetterFunctions.put("statut", Visite::getStatut);
			attributeGetterFunctions.put(
				"typeControle", Visite::getTypeControle);
			attributeGetterFunctions.put("dateVisite", Visite::getDateVisite);
			attributeGetterFunctions.put("compteRendu", Visite::getCompteRendu);
			attributeGetterFunctions.put("createdAt", Visite::getCreatedAt);
			attributeGetterFunctions.put("updatedAt", Visite::getUpdatedAt);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Visite, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Visite, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Visite, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Visite, Long>)Visite::setId);
			attributeSetterBiConsumers.put(
				"commercialId",
				(BiConsumer<Visite, Long>)Visite::setCommercialId);
			attributeSetterBiConsumers.put(
				"terminalId", (BiConsumer<Visite, Long>)Visite::setTerminalId);
			attributeSetterBiConsumers.put(
				"latitude", (BiConsumer<Visite, Double>)Visite::setLatitude);
			attributeSetterBiConsumers.put(
				"longitude", (BiConsumer<Visite, Double>)Visite::setLongitude);
			attributeSetterBiConsumers.put(
				"statut", (BiConsumer<Visite, String>)Visite::setStatut);
			attributeSetterBiConsumers.put(
				"typeControle",
				(BiConsumer<Visite, String>)Visite::setTypeControle);
			attributeSetterBiConsumers.put(
				"dateVisite", (BiConsumer<Visite, Date>)Visite::setDateVisite);
			attributeSetterBiConsumers.put(
				"compteRendu",
				(BiConsumer<Visite, String>)Visite::setCompteRendu);
			attributeSetterBiConsumers.put(
				"createdAt", (BiConsumer<Visite, Date>)Visite::setCreatedAt);
			attributeSetterBiConsumers.put(
				"updatedAt", (BiConsumer<Visite, Date>)Visite::setUpdatedAt);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCommercialId() {
		return _commercialId;
	}

	@Override
	public void setCommercialId(long commercialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialId = commercialId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommercialId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commercial_id"));
	}

	@Override
	public long getTerminalId() {
		return _terminalId;
	}

	@Override
	public void setTerminalId(long terminalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_terminalId = terminalId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTerminalId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("terminal_id"));
	}

	@Override
	public Double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(Double latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@Override
	public Double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(Double longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	@Override
	public String getStatut() {
		if (_statut == null) {
			return "";
		}
		else {
			return _statut;
		}
	}

	@Override
	public void setStatut(String statut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statut = statut;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatut() {
		return getColumnOriginalValue("statut");
	}

	@Override
	public String getTypeControle() {
		if (_typeControle == null) {
			return "";
		}
		else {
			return _typeControle;
		}
	}

	@Override
	public void setTypeControle(String typeControle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeControle = typeControle;
	}

	@Override
	public Date getDateVisite() {
		return _dateVisite;
	}

	@Override
	public void setDateVisite(Date dateVisite) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateVisite = dateVisite;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDateVisite() {
		return getColumnOriginalValue("date_visite");
	}

	@Override
	public String getCompteRendu() {
		if (_compteRendu == null) {
			return "";
		}
		else {
			return _compteRendu;
		}
	}

	@Override
	public void setCompteRendu(String compteRendu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_compteRendu = compteRendu;
	}

	@Override
	public Date getCreatedAt() {
		return _createdAt;
	}

	@Override
	public void setCreatedAt(Date createdAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return _updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedAt = updatedAt;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Visite.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Visite toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Visite>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VisiteImpl visiteImpl = new VisiteImpl();

		visiteImpl.setId(getId());
		visiteImpl.setCommercialId(getCommercialId());
		visiteImpl.setTerminalId(getTerminalId());
		visiteImpl.setLatitude(getLatitude());
		visiteImpl.setLongitude(getLongitude());
		visiteImpl.setStatut(getStatut());
		visiteImpl.setTypeControle(getTypeControle());
		visiteImpl.setDateVisite(getDateVisite());
		visiteImpl.setCompteRendu(getCompteRendu());
		visiteImpl.setCreatedAt(getCreatedAt());
		visiteImpl.setUpdatedAt(getUpdatedAt());

		visiteImpl.resetOriginalValues();

		return visiteImpl;
	}

	@Override
	public Visite cloneWithOriginalValues() {
		VisiteImpl visiteImpl = new VisiteImpl();

		visiteImpl.setId(this.<Long>getColumnOriginalValue("id"));
		visiteImpl.setCommercialId(
			this.<Long>getColumnOriginalValue("commercial_id"));
		visiteImpl.setTerminalId(
			this.<Long>getColumnOriginalValue("terminal_id"));
		visiteImpl.setLatitude(this.<Double>getColumnOriginalValue("latitude"));
		visiteImpl.setLongitude(
			this.<Double>getColumnOriginalValue("longitude"));
		visiteImpl.setStatut(this.<String>getColumnOriginalValue("statut"));
		visiteImpl.setTypeControle(
			this.<String>getColumnOriginalValue("type_controle"));
		visiteImpl.setDateVisite(
			this.<Date>getColumnOriginalValue("date_visite"));
		visiteImpl.setCompteRendu(
			this.<String>getColumnOriginalValue("compte_rendu"));
		visiteImpl.setCreatedAt(
			this.<Date>getColumnOriginalValue("created_at"));
		visiteImpl.setUpdatedAt(
			this.<Date>getColumnOriginalValue("updated_at"));

		return visiteImpl;
	}

	@Override
	public int compareTo(Visite visite) {
		int value = 0;

		value = DateUtil.compareTo(getDateVisite(), visite.getDateVisite());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Visite)) {
			return false;
		}

		Visite visite = (Visite)object;

		long primaryKey = visite.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Visite> toCacheModel() {
		VisiteCacheModel visiteCacheModel = new VisiteCacheModel();

		visiteCacheModel.id = getId();

		visiteCacheModel.commercialId = getCommercialId();

		visiteCacheModel.terminalId = getTerminalId();

		Double latitude = getLatitude();

		if (latitude != null) {
			visiteCacheModel.latitude = latitude;
		}

		Double longitude = getLongitude();

		if (longitude != null) {
			visiteCacheModel.longitude = longitude;
		}

		visiteCacheModel.statut = getStatut();

		String statut = visiteCacheModel.statut;

		if ((statut != null) && (statut.length() == 0)) {
			visiteCacheModel.statut = null;
		}

		visiteCacheModel.typeControle = getTypeControle();

		String typeControle = visiteCacheModel.typeControle;

		if ((typeControle != null) && (typeControle.length() == 0)) {
			visiteCacheModel.typeControle = null;
		}

		Date dateVisite = getDateVisite();

		if (dateVisite != null) {
			visiteCacheModel.dateVisite = dateVisite.getTime();
		}
		else {
			visiteCacheModel.dateVisite = Long.MIN_VALUE;
		}

		visiteCacheModel.compteRendu = getCompteRendu();

		String compteRendu = visiteCacheModel.compteRendu;

		if ((compteRendu != null) && (compteRendu.length() == 0)) {
			visiteCacheModel.compteRendu = null;
		}

		Date createdAt = getCreatedAt();

		if (createdAt != null) {
			visiteCacheModel.createdAt = createdAt.getTime();
		}
		else {
			visiteCacheModel.createdAt = Long.MIN_VALUE;
		}

		Date updatedAt = getUpdatedAt();

		if (updatedAt != null) {
			visiteCacheModel.updatedAt = updatedAt.getTime();
		}
		else {
			visiteCacheModel.updatedAt = Long.MIN_VALUE;
		}

		return visiteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Visite, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Visite, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Visite, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Visite)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Visite>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Visite.class, ModelWrapper.class);

	}

	private long _id;
	private long _commercialId;
	private long _terminalId;
	private Double _latitude;
	private Double _longitude;
	private String _statut;
	private String _typeControle;
	private Date _dateVisite;
	private String _compteRendu;
	private Date _createdAt;
	private Date _updatedAt;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Visite, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Visite)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("commercial_id", _commercialId);
		_columnOriginalValues.put("terminal_id", _terminalId);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
		_columnOriginalValues.put("statut", _statut);
		_columnOriginalValues.put("type_controle", _typeControle);
		_columnOriginalValues.put("date_visite", _dateVisite);
		_columnOriginalValues.put("compte_rendu", _compteRendu);
		_columnOriginalValues.put("created_at", _createdAt);
		_columnOriginalValues.put("updated_at", _updatedAt);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("commercial_id", "commercialId");
		attributeNames.put("terminal_id", "terminalId");
		attributeNames.put("type_controle", "typeControle");
		attributeNames.put("date_visite", "dateVisite");
		attributeNames.put("compte_rendu", "compteRendu");
		attributeNames.put("created_at", "createdAt");
		attributeNames.put("updated_at", "updatedAt");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("commercial_id", 2L);

		columnBitmasks.put("terminal_id", 4L);

		columnBitmasks.put("latitude", 8L);

		columnBitmasks.put("longitude", 16L);

		columnBitmasks.put("statut", 32L);

		columnBitmasks.put("type_controle", 64L);

		columnBitmasks.put("date_visite", 128L);

		columnBitmasks.put("compte_rendu", 256L);

		columnBitmasks.put("created_at", 512L);

		columnBitmasks.put("updated_at", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Visite _escapedModel;

}