/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.df.lonis.ventesservice.model.impl;

import com.df.lonis.ventesservice.model.Visite;
import com.df.lonis.ventesservice.service.VisiteLocalServiceUtil;

/**
 * The extended model base implementation for the Visite service. Represents a row in the &quot;visites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VisiteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisiteImpl
 * @see Visite
 * @generated
 */
public abstract class VisiteBaseImpl extends VisiteModelImpl implements Visite {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a visite model instance should use the <code>Visite</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			VisiteLocalServiceUtil.addVisite(this);
		}
		else {
			VisiteLocalServiceUtil.updateVisite(this);
		}
	}

}