spring.datasource.url=jdbc:postgresql://localhost:5432/l_caisse_new_db
spring.datasource.username=diginUser
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.df.lonis=DEBUG
logging.level.org.hibernate.SQL=DEBUG